### PR TITLE
Update build and test instructions

### PR DESCRIPTION
**Pull request by jwcroppe**
This patch updates the build and test instructions and also corrects
the minimal level of Golang required.

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/180)

### CODE REVIEW

**Comment by alonm** [comment]
isn't this the same as PR 178?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/180#-:-L3Rf7UJwM9vPLVoGbzS:by6zyyi)*

**Comment by jwcroppe** [comment]
@alonm Yes, but I just rebased it against the dev stream to keep the commit log clean.

**Comment by alonm** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/180#-:-L3X_k5NDxxZCJkTpmN0:bnfp4nl)*

**Comment by jwcroppe** [comment]
@alonm Thanks!
@shay-berman Any feedback on this patch set?

**Comment by shay-berman** [comment]
@jwcroppe thanks for this PR
Since we already update the contribution md file with more details as part of v1.1, this PR is less relevant. So I am closing it.

Note: later on we plan to add more details inside such as how to run unit tests in the docker image it self.

**Pull request closed without merging**
