### PR TITLE
Spectrumscale epic2

### PR DESCRIPTION
**Pull request by deeghuge**
- Removed ssh and mmcli connector support from spectrum scale
- Removed NFS and LightWeight backend support from spectrum scale
- Changes for using postgresql for databases instead of sqlite.
- Changes in Rest v2 - Using the different mechanism to check filesystem is mounted or not
- Added support for accepting ssl ca-certificate for Communication between ubiquity server and Spectrum scale rest api server. 
- Use of new logger, fixes for UT and removed scale specific error.go instead using errors from resource.
- Removed spectrum scale specific activation check while activating Provisioner and flex.

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/249)

### CODE REVIEW

**Comment by yadaven** [comment]
___
*[local/spectrumscale/spectrumscale.go, line 386 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOSlbHr0rGWeNs2d6ZI:-LOT1E2i2KO0O8NSr7lG:b-q0layy) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/spectrumscale/spectrumscale.go#L386)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

why u need to run it agai
</blockquote></details>

If volume is not DB volume we need to create it 
OR
In case dbVolume is not present we want to create it.
Just above this check we verify if it is Dbvolume and checks for its existence.

**Comment by yadaven** [comment]
___
*[local/spectrumscale/spectrumscale.go, line 383 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOSlU-q8c0Vhl40Ayrr:-LOT1mVp44aYSTBjFilm:bon2i87) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/spectrumscale/spectrumscale.go#L383)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

what about error handling?

i think u have a bug here
</blockquote></details>

Here we mainly checks for existence of DbVolume and based on return value we create it.

**Comment by shay-berman** [comment]
Hi @deeghuge  , I finished to review it.  please go though and apply my and Olga comments. Then let us know again for another review before merging.

**Comment by yadaven** [comment]
___
*[local/spectrumscale/spectrumscale.go, line 556 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOXHdh9DLt_4fQWYatq:-LOrOxpICdePLhbKZjyi:b-o34wym) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/spectrumscale/spectrumscale.go#L556)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

r u using the right logger?
just double check 
</blockquote></details>

yes we are using correct logger

**Comment by yadaven** [comment]
___
*[local/clients.go, line 42 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOS0vGK5dTMT3rPe7cw:-LOrTPXZ9eELENQXNNDQ:bd3lmpj) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/clients.go#L42)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

i think we should improve it.
we hide the error in the log message.  lets show the error instead of hiding it. (fix it for both scbe and scale)

In addition why you are not using here the new logger? with Debug?  lets consider to just use it in standard way of loggign.
</blockquote></details>

If initialisation of any backend fails then we return error, for this we have introduced new error i.e. BackendInitializationError.  Also made changes to use new Logger function.

**Comment by yadaven** [comment]
___
*[local/clients.go, line 49 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOS1rll5dsHecC4Om0o:-LOrTtBf33MzEU5Q6DIA:bi19cr8) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/clients.go#L49)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

fix text please and use Error() of the new logger.

text should be "check backend configuration - Scale ManagementIP  or SpectrumConnect managmentIP is mandator in the ubiqutiy-configmap "
</blockquote></details>

made changes to use logger.ErrorRet with the proposed error text.

**Comment by yadaven** [comment]
___
*[local/spectrumscale/spectrumscale.go, line 72 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOSQ-p90t6GTtPQrIGa:-LOrUPZk74jhpW--jiky:b-ayi751) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/spectrumscale/spectrumscale.go#L72)):*
<details><summary><i>Previously, olgashtivelman wrote…</i></summary><blockquote>

 maybe you want to use logger.Error/Warning here? (and for the other errors as well)  so that it will be recorded in the logs even if its not in debug mode? 
</blockquote></details>

using logger.ErrorRet to return error.

**Comment by yadaven** [comment]
___
*[local/spectrumscale/spectrumscale.go, line 230 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOSjHGG7415bfRD8fvp:-LOrUb31EEcAlHz1hB10:b4uoae6) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/spectrumscale/spectrumscale.go#L230)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

remove this line and the second
instead do 
return logger.ErrorRet(err, "short description")

you can see other places.
</blockquote></details>

made the proposed changes

**Comment by yadaven** [comment]
___
*[local/spectrumscale/spectrumscale.go, line 238 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOSjYIp7EOiZn3VH8dc:-LOrUf9c9AGQUFXYbcrh:b6lj7u0) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/spectrumscale/spectrumscale.go#L238)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

the same

and i see many other places - so please apply to all of them
</blockquote></details>

took care of this in almost all places.

**Comment by yadaven** [comment]
___
*[local/spectrumscale/spectrumscale.go, line 267 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOSkc1z5Am-Izz7-1I_:-LOrUrdZ0E9d_1Ge1gJE:bpgrlfb) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/spectrumscale/spectrumscale.go#L267)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

the attach is less important here
consider even to delete it
because from what I know this function will never called right?

if so then i don't care about its code. 
please clarify
</blockquote></details>

made Attach/Detach to return success. It is needed since we use StorageClient Interface. Removed Attach/Detach UT

**Comment by yadaven** [comment]
___
*[local/spectrumscale/spectrumscale.go, line 309 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOSklna3Vb4rdcxlRkh:-LOrV5FSARfGhbtsz5ey:b-55oo09) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/spectrumscale/spectrumscale.go#L309)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

same as the attach

note if u don't use it then its better to avoid adding it here.  because u need to add UT for it.
and also if have some idempotent aspects here that you are not handling

so please decide - is this code for v2 relevant? if not then drop it or put in a comment
</blockquote></details>

Made Detach to always return success. Removed UT

**Comment by yadaven** [comment]
___
*[local/spectrumscale/spectrumscale.go, line 353 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOSl0NkByyWWRfl-RPS:-LOrVE92C0gUyg9_SNuJ:b3lojwq) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/spectrumscale/spectrumscale.go#L353)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

not debug
</blockquote></details>

Changed to use logger.ErrorRet

**Comment by yadaven** [comment]
___
*[local/spectrumscale/spectrumscale.go, line 618 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOXI5_nCa729pXYIkHR:-LOrVQbaAAlAFFtBXJuk:bb6un1j) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/spectrumscale/spectrumscale.go#L618)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

you can use the logger function so it will go also to the log and then return the error. mentioned it in the past
</blockquote></details>

Done

**Comment by yadaven** [comment]
___
*[local/spectrumscale/spectrumscale.go, line 628 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOXIEKf0sk1hu1HLlXa:-LOrVfl92Upq0m7MyZ0R:bq5lw4g) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/spectrumscale/spectrumscale.go#L628)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

r u sure about this 777?

please make sure you align with security aspects, maybe it should take premission from user define.
please double checkit.,
</blockquote></details>

Changes it to 750

**Comment by shay-berman** [comment]
Hi @deeghuge , I finished the second review on this PR.
Please try to resolve all the comments and let me know when its ready.
Thanks

**Comment by yadaven** [comment]
___
*[local/clients.go, line 42 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOS0vGK5dTMT3rPe7cw:-LOvMFw3D6LFCeqCt0Vy:bxtkc29) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/clients.go#L42)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

but on this line  you hide the real error "err" from the backendinitilizationError.  So you can add the err into this BackendInitializationError so it will be visible and not hiden

Does it make sense?
</blockquote></details>

I agree. Made changes such that BackendInitializationError also have error field and we print this error.

**Comment by yadaven** [comment]
___
*[local/spectrumscale/datamodel_wrapper.go, line 1 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOS2zT36pOgxxJYay2_:-LOvMYWaAgAcBdl9cDdP:by940fo) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/spectrumscale/datamodel_wrapper.go#L1)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

waiting for your reply.
</blockquote></details>

made it 2018

**Comment by yadaven** [comment]
___
*[local/spectrumscale/spectrumscale.go, line 386 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOSlbHr0rGWeNs2d6ZI:-LOvOOuu1mqYpWiY_0ex:beu780) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/spectrumscale/spectrumscale.go#L386)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

> ```
> s.dataModel.IsDbVolume(name)
> ```
yes but why to run "s.dataModel.IsDbVolume(name)" twice in the same function?  you can run it once and reuse it 2 lines later on.
make sense?
</blockquote></details>

agree. Took s.dataModel.IsDbVolume output in a variable and used it in both places

**Comment by yadaven** [comment]
___
*[local/spectrumscale/spectrumscale.go, line 522 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOXHA3L6v5otWwgBVnJ:-LOvOf1-A6hU872--Hcf:b-xueh46) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/spectrumscale/spectrumscale.go#L522)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

please reply
</blockquote></details>

That's right, it is static info and we update quota only during volume creation and is not changed later on.

**Comment by yadaven** [comment]
___
*[local/spectrumscale/connectors/connectors.go, line 53 at r5](https://reviewable.io/reviews/ibm/ubiquity/249#-LOrtFJi9cOw3m8lbryP:-LOvP5OP2NegyWnVaqHO:blsyav) ([raw file](https://github.com/ibm/ubiquity/blob/03e7017cd7e21eb1dbe03e9cbffc202b890edc08/local/spectrumscale/connectors/connectors.go#L53)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

don't u want to use the standard logger?
</blockquote></details>

We are using standard logger here. Also added  logger.Trace for this function.

**Comment by yadaven** [comment]
___
*[local/spectrumscale/connectors/resources.go, line 312 at r5](https://reviewable.io/reviews/ibm/ubiquity/249#-LOrtOw81tbd2XywUQkf:-LOvPHALEbasUjdqhzOa:b-hjsq6m) ([raw file](https://github.com/ibm/ubiquity/blob/03e7017cd7e21eb1dbe03e9cbffc202b890edc08/local/spectrumscale/connectors/resources.go#L312)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

is this Scale specific?  if so maybe add Scale as prefix.
</blockquote></details>

These structures are defined in ubiquity/local/spectrumscale/connectors/resources.go file which is specific to SpectrumScale. Since this is specific to Scale I think no need to add Scale Prefix.  Kindly let us know if you agree with this.

**Comment by yadaven** [comment]
___
*[resources/resources.go, line 89 at r5](https://reviewable.io/reviews/ibm/ubiquity/249#-LOrtc7o3fu32Trji9OZ:-LOvQ9NV7aEd8QRIC_IV:bb6un1j) ([raw file](https://github.com/ibm/ubiquity/blob/03e7017cd7e21eb1dbe03e9cbffc202b890edc08/resources/resources.go#L89)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

BTW you can just reuse the scaleprefix above here in the text instead of duplicate the prefix.
</blockquote></details>

Done

**Comment by yadaven** [comment]
___
*[local/clients_test.go, line 37 at r4](https://reviewable.io/reviews/ibm/ubiquity/249#-LOS2c-H0zKhs6Kncc0e:-LP-Ws_d73VkKuRojXhN:be9jgyr) ([raw file](https://github.com/ibm/ubiquity/blob/c2d5f426251323dc3c691bb35da063239f381777/local/clients_test.go#L37)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

Any response here?
</blockquote></details>

Added UT for all cases.

**Comment by shay-berman** [comment]
**You have LGTM from CI testing.**

@deeghuge  you have green light from CI staging for merging this PR to dev.
Remember to merge it with squash commits and also remember also to update the ubiqutiy-k8s 
 glide.yml in https://github.com/IBM/ubiquity-k8s/pull/216  with the latest ubiquity commit (after you merge this ubiqutiy PR first) and then merge it as well to dev.

**Pull request merged**
