### PR TITLE
Improve umount flow tolerance

### PR DESCRIPTION
**Pull request by shay-berman**
---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/163)

### CODE REVIEW

**Comment by ranhrl** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[remote/mounter/block_device_utils/fs.go, line 90 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/163#-L-XxT23-tzK3Y7Jg4aN:-L-XxT23-tzK3Y7Jg4aO:b-sahtb0) ([raw file](https://github.com/ibm/ubiquity/blob/a34aac4ed6adf75afab313ab1bd8127018b87791/remote/mounter/block_device_utils/fs.go#L90)):*
> ```Go
> 	if _, err := b.exec.Execute(umountCmd, args); err != nil {
> 		if b.regExAlreadyMounted.MatchString(err.Error()) {
> 			b.logger.Info("Already umounted, so skip the umount operation.", logs.Args{{"mpoint", mpoint}})
> ```

Is it wise to count on specific error messages to return as text? I suggest 2 other options, either check the return code or check if it is mounted before running unmount (or after). What if the error message will change? For example, on mac you get "not currently mounted" which does not match your regexp.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/163)*

**Comment by shay-berman** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[remote/mounter/block_device_utils/fs.go, line 90 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/163#-L-XxT23-tzK3Y7Jg4aN:-L-Z73SqQN1aJXJr_k4r:bmuu3bz) ([raw file](https://github.com/ibm/ubiquity/blob/a34aac4ed6adf75afab313ab1bd8127018b87791/remote/mounter/block_device_utils/fs.go#L90)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

Is it wise to count on specific error messages to return as text? I suggest 2 other options, either check the return code or check if it is mounted before running unmount (or after). What if the error message will change? For example, on mac you get "not currently mounted" which does not match your regexp.
</blockquote></details>

- we support only ubuntu and rhel, and in both this is the error message in this case
- anyway, it took me 3 hours to change it from identify mounted based on error message to identify it via mount command.  Took me while because I am in jet leg time :-)
- Ran please review again

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/163)*

**Comment by ranhrl** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[remote/mounter/block_device_utils/fs.go, line 90 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/163#-L-XxT23-tzK3Y7Jg4aN:-L-_YWfnxePaZDbHiLLb:bioh9un) ([raw file](https://github.com/ibm/ubiquity/blob/a34aac4ed6adf75afab313ab1bd8127018b87791/remote/mounter/block_device_utils/fs.go#L90)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

- we support only ubuntu and rhel, and in both this is the error message in this case
- anyway, it took me 3 hours to change it from identify mounted based on error message to identify it via mount command.  Took me while because I am in jet leg time :-)
- Ran please review again
</blockquote></details>

Looks good to me. The only philosophical question I have is do we want to check if the mount point exists before umount every time or just if umount fails. Since most of the times we do expect it to be mounted, it might be wiser, what do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/163)*

**Comment by shay-berman** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[remote/mounter/block_device_utils/fs.go, line 90 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/163#-L-XxT23-tzK3Y7Jg4aN:-L-af6YhZ5e0Q6mUfUk_:b-yvw4c4) ([raw file](https://github.com/ibm/ubiquity/blob/a34aac4ed6adf75afab313ab1bd8127018b87791/remote/mounter/block_device_utils/fs.go#L90)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

Looks good to me. The only philosophical question I have is do we want to check if the mount point exists before umount every time or just if umount fails. Since most of the times we do expect it to be mounted, it might be wiser, what do you think?
</blockquote></details>

you are killing me :-)

I think i agree with you on that. Please tell lior\Tzur to apply this change if u want. I have no time for this now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/163)*

**Comment by ranhrl** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/163#-:-L-bVuj2XIq_QOyH4K31:bnfp4nl)*

**Pull request merged**
