### PR TITLE
Merge dev GA v1.0.0 to master branch

### PR DESCRIPTION
**Pull request by shay-berman**
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/176)

### CODE REVIEW

**Comment by ranhrl** [comment]
:lgtm:

---

Review status: 0 of 84 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/176#-:-L0iZNeegRAuU7eoK7zn:bnfp4nl)*

**Comment by ranhrl** [comment]
Reviewed 84 of 84 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/176)*

**Comment by alonm** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/176#-:-L0idGVtLk-vPPzaPFuI:bnfp4nl)*

**Comment by alonm** [comment]
Reviewed 84 of 84 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/176)*

**Comment by shay-berman** [comment]
Reviewed 74 of 84 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/176)*

**Pull request merged**
