### PR TITLE
Added a double validation for multipath device WWN discovered via multipath -ll

### PR DESCRIPTION
**Pull request by tzurE**
…ests.

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/164)

### CODE REVIEW

**Comment by ranhrl** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[remote/mounter/block_device_utils/mpath.go, line 87 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/164#-L-gWeLB1Yk9-UvVWBdL:-L-gWeLB1Yk9-UvVWBdM:b-qzpin4) ([raw file](https://github.com/ibm/ubiquity/blob/fe3ce0187356feec9c2758db3017441c4f2aa4c5/remote/mounter/block_device_utils/mpath.go#L87)):*
> ```Go
> 	}
> 	if _, err = b.exec.Stat(mpath); err != nil {
> 		return "", b.logger.ErrorRet(err, "Stat failed")
> ```

I know it's not in this code change but can we do better with this error message? Stat failed for volume [%s] ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/164)*

**Comment by ranhrl** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/164#-:-L-gWpn4LCMFwzreEhjD:bnfp4nl)*

**Comment by shay-berman** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[remote/mounter/block_device_utils/errors.go, line 47 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/164#-L-gXeGL4IgvmFOtSpr5:-L-gXeGL4IgvmFOtSpr6:b8o5uv5) ([raw file](https://github.com/ibm/ubiquity/blob/fe3ce0187356feec9c2758db3017441c4f2aa4c5/remote/mounter/block_device_utils/errors.go#L47)):*
> ```Go
> }
> 
> type wrongVolumeFoundError struct {
> ```

rename to wrongDeviceFoundError

---

*[remote/mounter/block_device_utils/errors.go, line 49 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/164#-L-gXqSn_EqdK66ObILl:-L-gXqSn_EqdK66ObILm:b4zivhb) ([raw file](https://github.com/ibm/ubiquity/blob/fe3ce0187356feec9c2758db3017441c4f2aa4c5/remote/mounter/block_device_utils/errors.go#L49)):*
> ```Go
> type wrongVolumeFoundError struct {
> 	volName string
> 	reqVolName string
> ```

Add also the dev path as argument

---

*[remote/mounter/block_device_utils/errors.go, line 52 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/164#-L-gXvDj7TuQCLm1ehPz:-L-gXvDj7TuQCLm1ehQ-:byvdy6u) ([raw file](https://github.com/ibm/ubiquity/blob/fe3ce0187356feec9c2758db3017441c4f2aa4c5/remote/mounter/block_device_utils/errors.go#L52)):*
> ```Go
> }
> func (e *wrongVolumeFoundError) Error() string {
> 	return fmt.Sprintf("volume [%v] is not found. instead found vol [%s].", e.reqVolName, e.volName)
> ```

fix it to
"multipath device [%s] was found as WWN [%v] via multipath -ll command, BUT sg_inq identify this device as different WWN [%s]. Check your multipathd."

---

*[remote/mounter/block_device_utils/mpath.go, line 79 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/164#-L-gXFPmeKEudQFMWFET:-L-gXFPnTuTOHKcwQzos:bwgzag6) ([raw file](https://github.com/ibm/ubiquity/blob/fe3ce0187356feec9c2758db3017441c4f2aa4c5/remote/mounter/block_device_utils/mpath.go#L79)):*
> GetWwnByScsiInq
please call the var, SqInqWwn

---

*[remote/mounter/block_device_utils/mpath.go, line 84 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/164#-L-gXUSNR18nAsdU-14F:-L-gXUSNR18nAsdU-14G:bczaatn) ([raw file](https://github.com/ibm/ubiquity/blob/fe3ce0187356feec9c2758db3017441c4f2aa4c5/remote/mounter/block_device_utils/mpath.go#L84)):*
> ```Go
> 	}
> 	if strings.ToLower(wwn) != strings.ToLower(volumeWwn){
> 		return "", b.logger.ErrorRet(&wrongVolumeFoundError{wwn, volumeWwn}, "failed")
> ```

please add here also dev as argument to see the whole picture not only the WWN

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/164)*

**Comment by tzurE** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[remote/mounter/block_device_utils/errors.go, line 47 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/164#-L-gXeGL4IgvmFOtSpr5:-L-kFNgy2_p6qqSJyLdN:b-896fix) ([raw file](https://github.com/ibm/ubiquity/blob/fe3ce0187356feec9c2758db3017441c4f2aa4c5/remote/mounter/block_device_utils/errors.go#L47)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

rename to wrongDeviceFoundError
</blockquote></details>

Done.

---

*[remote/mounter/block_device_utils/errors.go, line 49 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/164#-L-gXqSn_EqdK66ObILl:-L-kFw9wZPS5XZeLCJgw:b-896fix) ([raw file](https://github.com/ibm/ubiquity/blob/fe3ce0187356feec9c2758db3017441c4f2aa4c5/remote/mounter/block_device_utils/errors.go#L49)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

Add also the dev path as argument
</blockquote></details>

Done.

---

*[remote/mounter/block_device_utils/errors.go, line 52 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/164#-L-gXvDj7TuQCLm1ehPz:-L-kHlSjoAn8fiqlVvm_:b-896fix) ([raw file](https://github.com/ibm/ubiquity/blob/fe3ce0187356feec9c2758db3017441c4f2aa4c5/remote/mounter/block_device_utils/errors.go#L52)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

fix it to
"multipath device [%s] was found as WWN [%v] via multipath -ll command, BUT sg_inq identify this device as different WWN [%s]. Check your multipathd."
</blockquote></details>

Done.

---

*[remote/mounter/block_device_utils/mpath.go, line 79 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/164#-L-gXFPmeKEudQFMWFET:-L-kHrvFRsIHQP_hw3dr:b-896fix) ([raw file](https://github.com/ibm/ubiquity/blob/fe3ce0187356feec9c2758db3017441c4f2aa4c5/remote/mounter/block_device_utils/mpath.go#L79)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

> GetWwnByScsiInq
please call the var, SqInqWwn
</blockquote></details>

Done.

---

*[remote/mounter/block_device_utils/mpath.go, line 84 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/164#-L-gXUSNR18nAsdU-14F:-L-kHy9A_NJiGZoBnVKF:b-896fix) ([raw file](https://github.com/ibm/ubiquity/blob/fe3ce0187356feec9c2758db3017441c4f2aa4c5/remote/mounter/block_device_utils/mpath.go#L84)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

please add here also dev as argument to see the whole picture not only the WWN
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/164)*

**Comment by shay-berman** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[remote/mounter/block_device_utils/block_device_utils_test.go, line 177 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/164#-L-l-ehFncWvoCQmK7Tu:-L-l-ehFncWvoCQmK7Tv:b-sxg48z) ([raw file](https://github.com/ibm/ubiquity/blob/e0b0342e8de68fefeaa8fb246d3206727eb24247/remote/mounter/block_device_utils/block_device_utils_test.go#L177)):*
> ```Go
> 			Expect(err.Error()).To(MatchRegexp(cmdErr.Error()))
> 		})
> 		It("Discover fails if wrong wwn is found", func() {
> ```

very good UT

---

*[remote/mounter/block_device_utils/block_device_utils_test.go, line 199 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/164#-L-l-s6YIX0mfCHZL9xV:-L-l-s6YIX0mfCHZL9xW:b-cycdvw) ([raw file](https://github.com/ibm/ubiquity/blob/e0b0342e8de68fefeaa8fb246d3206727eb24247/remote/mounter/block_device_utils/block_device_utils_test.go#L199)):*
> ```Go
> 			cmd, args = fakeExec.ExecuteArgsForCall(1)
> 			Expect(cmd).To(Equal("sg_inq"))
> 			Expect(args).To(Equal([]string{"-p",  "0x83", "/dev/mapper/mpath"}))
> ```

not must, but its better to use the "/dev/mapper/" + result

---

*[remote/mounter/block_device_utils/errors.go, line 52 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/164#-L-gXvDj7TuQCLm1ehPz:-L-l0M3SFJvhpffGltVK:b-t2549q) ([raw file](https://github.com/ibm/ubiquity/blob/fe3ce0187356feec9c2758db3017441c4f2aa4c5/remote/mounter/block_device_utils/errors.go#L52)):*
<details><summary><i>Previously, tzurE wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Do you think we should tell Dima to add this string to the troubleshooting section in the userguide?

---

*[remote/mounter/block_device_utils/mpath.go, line 87 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/164#-L-gWeLB1Yk9-UvVWBdL:-L-l1D_Q1OuW0PPlCnNk:b-legz4e) ([raw file](https://github.com/ibm/ubiquity/blob/fe3ce0187356feec9c2758db3017441c4f2aa4c5/remote/mounter/block_device_utils/mpath.go#L87)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

I know it's not in this code change but can we do better with this error message? Stat failed for volume [%s] ?
</blockquote></details>

the err it should will be find not found. so i think we are ok here.  But yes we can add here "Stat fileX failed".
BTW this is the same Stat we should do after remove the multipath device.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/164)*

**Comment by tzurE** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[remote/mounter/block_device_utils/block_device_utils_test.go, line 199 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/164#-L-l-s6YIX0mfCHZL9xV:-L-lfGNqk6-S0zVMyb59:b-896fix) ([raw file](https://github.com/ibm/ubiquity/blob/e0b0342e8de68fefeaa8fb246d3206727eb24247/remote/mounter/block_device_utils/block_device_utils_test.go#L199)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

not must, but its better to use the "/dev/mapper/" + result
</blockquote></details>

Done.

---

*[remote/mounter/block_device_utils/errors.go, line 52 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/164#-L-gXvDj7TuQCLm1ehPz:-L-lfJ5s9G9T1b7ahIF3:b2nign6) ([raw file](https://github.com/ibm/ubiquity/blob/fe3ce0187356feec9c2758db3017441c4f2aa4c5/remote/mounter/block_device_utils/errors.go#L52)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

Do you think we should tell Dima to add this string to the troubleshooting section in the userguide?
</blockquote></details>

yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/164)*

**Pull request merged**
