### PR TITLE
Fix/ub 624 flex should not write log into flex driver directory

### PR DESCRIPTION
**Pull request by hfeish**
1. Handle flex logrotate internal
2. configurable for FLEX-LOG-DIR in ubiquity-configmap.yml and ubiquity_installer.conf, default is /var/log, customer need to make sure Flex-Log-dir exist in the minors
3. configurable for FLEX-LOG-ROTATE-MAXSIZE in ubiquity-configmap.yml, default is 50MB
Need to work with https://github.com/IBM/ubiquity-k8s/pull/163

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/181)

### CODE REVIEW

**Comment by shay-berman** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[utils/logs/global_logger.go, line 25 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/181#-L4oCZTyJqyg_vxJsG7Y:-L4oCZTyJqyg_vxJsG7Z:bmf8hvq) ([raw file](https://github.com/ibm/ubiquity/blob/80e6d4bbbf349692c2b33e998ee9c45fd86705dc/utils/logs/global_logger.go#L25)):*
> ```Go
> 	"path"
> 	"strings"
> 	"github.com/natefinch/lumberjack"
> ```

send to Alon the new import link please.

---

*[utils/logs/global_logger.go, line 60 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/181#-L6QevQs5vValpLxCj1b:-L6QevQs5vValpLxCj1c:b9p0th) ([raw file](https://github.com/ibm/ubiquity/blob/80e6d4bbbf349692c2b33e998ee9c45fd86705dc/utils/logs/global_logger.go#L60)):*
> ```Go
> 	if os.IsNotExist(err) {
> 		fileDir,_ := path.Split(filePath)
> 		err := os.MkdirAll(fileDir, 0766)
> ```

but what if the directory already exist? (you check above if the file exist but what if the file not exist but the dir exist? you suould handle it as well) 

---

*[utils/logs/global_logger.go, line 76 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/181#-L4oDSJ6Cmt6Z3-Px9Tt:-L4oDSJ7eloRTowvSZcj:b-2paqbw) ([raw file](https://github.com/ibm/ubiquity/blob/80e6d4bbbf349692c2b33e998ee9c45fd86705dc/utils/logs/global_logger.go#L76)):*
> ```Go
> 	}
> 
> 	fileStatSize := int(fileStat.Size())
> ```

just do it in one line, instead of 2 lines

---

*[utils/logs/global_logger.go, line 79 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/181#-L4oDc0YAHIhR7aTwORA:-L4oDc0YAHIhR7aTwORB:bfx5dmc) ([raw file](https://github.com/ibm/ubiquity/blob/80e6d4bbbf349692c2b33e998ee9c45fd86705dc/utils/logs/global_logger.go#L79)):*
> ```Go
> 	fileStatSize = fileStatSize / 1024 / 1024
> 
> 	// If log file size bigger than 52428800 (50MB), will use lunberjack to run the logrotate
> ```

don't hardcoded in the comment the max size which is configurable.

---

*[utils/logs/global_logger.go, line 83 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/181#-L4oESE59fAfL56U7p2N:-L4oESE59fAfL56U7p2O:b-7et00m) ([raw file](https://github.com/ibm/ubiquity/blob/80e6d4bbbf349692c2b33e998ee9c45fd86705dc/utils/logs/global_logger.go#L83)):*
> ```Go
> 		initLogger(level, io.MultiWriter(logFile))
> 	} else {
> 		initLogger(level, &lumberjack.Logger{
> ```

what happened if 10 flex runs at the same time?
How this lumberhjack.Logger log rotate handle it?  please make sure we have no issue with concurrency 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/181)*

**Comment by shay-berman** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[utils/logs/global_logger.go, line 83 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/181#-L4oESE59fAfL56U7p2N:-L6QlnaILxH9oyjE80Kl:b2pnf6g) ([raw file](https://github.com/ibm/ubiquity/blob/80e6d4bbbf349692c2b33e998ee9c45fd86705dc/utils/logs/global_logger.go#L83)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

what happened if 10 flex runs at the same time?
How this lumberhjack.Logger log rotate handle it?  please make sure we have no issue with concurrency 
</blockquote></details>

Fie, did you tested it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/181)*

**Comment by shay-berman** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[utils/logs/global_logger.go, line 60 at r2](https://reviewable.io/reviews/ibm/ubiquity/181#-L6QevQs5vValpLxCj1b:-LB095Fn7MY6TllGPTix:b4qnyjp) ([raw file](https://github.com/ibm/ubiquity/blob/80e6d4bbbf349692c2b33e998ee9c45fd86705dc/utils/logs/global_logger.go#L60)):*
<details><summary><i>Previously, hfeish (Fei Huang) wrote…</i></summary><blockquote>

MkdirAll will do nothing if the dir exist but file not exist, so we can ignore this
</blockquote></details>

ok
please make sure you have UT for this

---

*[utils/logs/global_logger.go, line 83 at r2](https://reviewable.io/reviews/ibm/ubiquity/181#-L4oESE59fAfL56U7p2N:-LB0DEMy82pVjfmDgIcl:b-r8zp04) ([raw file](https://github.com/ibm/ubiquity/blob/80e6d4bbbf349692c2b33e998ee9c45fd86705dc/utils/logs/global_logger.go#L83)):*
<details><summary><i>Previously, hfeish (Fei Huang) wrote…</i></summary><blockquote>

https://wiki.xiv.ibm.com/display/HostSide/Flex+log+file+refactor
I had some tests about this and add some comments under the page, please take a look, thanks!
</blockquote></details>

whats happened if one flex rotate the file while other one write to it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/181)*

**Comment by hfeish** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[utils/logs/global_logger.go, line 60 at r2](https://reviewable.io/reviews/ibm/ubiquity/181#-L6QevQs5vValpLxCj1b:-LB16c8yEJanfZni9AIW:bq3j63g) ([raw file](https://github.com/ibm/ubiquity/blob/80e6d4bbbf349692c2b33e998ee9c45fd86705dc/utils/logs/global_logger.go#L60)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

ok
please make sure you have UT for this
</blockquote></details>

Add UT in the utils/logs/global_logger_test.go

---

*[utils/logs/global_logger.go, line 83 at r2](https://reviewable.io/reviews/ibm/ubiquity/181#-L4oESE59fAfL56U7p2N:-LB16hN1Cq_mdMUSa3Hk:bofkrd4) ([raw file](https://github.com/ibm/ubiquity/blob/80e6d4bbbf349692c2b33e998ee9c45fd86705dc/utils/logs/global_logger.go#L83)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

whats happened if one flex rotate the file while other one write to it?
</blockquote></details>

When we call InitFileLogger, it will init a logger, and before that we need to compare the log file size, if it < rotatesize, it will init a logger with io.MultiWriter, and if it > rotatesize, it will init a lumberjack.logger, and this logger will  rotate the log file, it will close the current logfile and renamed and a new log file created with original name.  Thus the filename you give logger is always the same file name. 
And since we rotate with 50MB default size, there is no much chance to do the logrotate every day

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/181)*

**Comment by shay-berman** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[utils/logs/global_logger.go, line 83 at r2](https://reviewable.io/reviews/ibm/ubiquity/181#-L4oESE59fAfL56U7p2N:-LBtgxr84o5zervmoSPE:b-1euitz) ([raw file](https://github.com/ibm/ubiquity/blob/80e6d4bbbf349692c2b33e998ee9c45fd86705dc/utils/logs/global_logger.go#L83)):*
<details><summary><i>Previously, hfeish (Fei Huang) wrote…</i></summary><blockquote>

When we call InitFileLogger, it will init a logger, and before that we need to compare the log file size, if it < rotatesize, it will init a logger with io.MultiWriter, and if it > rotatesize, it will init a lumberjack.logger, and this logger will  rotate the log file, it will close the current logfile and renamed and a new log file created with original name.  Thus the filename you give logger is always the same file name. 
And since we rotate with 50MB default size, there is no much chance to do the logrotate every day
</blockquote></details>

but please make sure flex handle log rotating while other flex also do the log rotating. This is not a rare scenario.

---

*[utils/logs/global_logger_test.go, line 3 at r3](https://reviewable.io/reviews/ibm/ubiquity/181#-LBthDmZ7DimUdnicI3b:-LBthDm_239h9_B8Fcv0:b-jxogvu) ([raw file](https://github.com/ibm/ubiquity/blob/a657c1b38f089ce891ba462afdac37c9fce1e948/utils/logs/global_logger_test.go#L3)):*
> ```Go
> package logs_test
> 
> import (
> ```

what is this test file
please mention who trigger this test and some detail how to run it.
Do we need to add it into CI?   provide more detail here please.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/181)*

**Comment by hfeish** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[utils/logs/global_logger.go, line 83 at r2](https://reviewable.io/reviews/ibm/ubiquity/181#-L4oESE59fAfL56U7p2N:-LCgis6C-NVcZns4-JML:b-9133ja) ([raw file](https://github.com/ibm/ubiquity/blob/80e6d4bbbf349692c2b33e998ee9c45fd86705dc/utils/logs/global_logger.go#L83)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

but please make sure flex handle log rotating while other flex also do the log rotating. This is not a rare scenario.
</blockquote></details>

I tried to attach 5 pods at same time, and it works and no error in log file, I think it meet the multi flex, right

---

*[utils/logs/global_logger_test.go, line 3 at r3](https://reviewable.io/reviews/ibm/ubiquity/181#-LBthDmZ7DimUdnicI3b:-LCgk5urAGrJNQ_320L6:bn67vo4) ([raw file](https://github.com/ibm/ubiquity/blob/a657c1b38f089ce891ba462afdac37c9fce1e948/utils/logs/global_logger_test.go#L3)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

what is this test file
please mention who trigger this test and some detail how to run it.
Do we need to add it into CI?   provide more detail here please.
</blockquote></details>

this is example test, dev trigger it with "go test -v", we don't need to add it into CI, because this test only prove the API works as expect just like Unit test.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/181)*

**Comment by shay-berman** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[utils/logs/global_logger_test.go, line 3 at r3](https://reviewable.io/reviews/ibm/ubiquity/181#-LBthDmZ7DimUdnicI3b:-LD6shr5-6fUjhMtPWUf:b-tnl2kn) ([raw file](https://github.com/ibm/ubiquity/blob/a657c1b38f089ce891ba462afdac37c9fce1e948/utils/logs/global_logger_test.go#L3)):*
<details><summary><i>Previously, hfeish (Fei Huang) wrote…</i></summary><blockquote>

this is example test, dev trigger it with "go test -v", we don't need to add it into CI, because this test only prove the API works as expect just like Unit test.
</blockquote></details>

how does "go test -v" trigger this file?    its not a testing or ginkgo file. What do I miss here?
Please add doc string in the beginning of the file that explain this test file.
Do you plan to trigger it during the scripts/run_units.sh ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/181)*

**Comment by hfeish** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[utils/logs/global_logger_test.go, line 3 at r3](https://reviewable.io/reviews/ibm/ubiquity/181#-LBthDmZ7DimUdnicI3b:-LDAFmFTEFJcavoXEhI8:b-2covme) ([raw file](https://github.com/ibm/ubiquity/blob/a657c1b38f089ce891ba462afdac37c9fce1e948/utils/logs/global_logger_test.go#L3)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

how does "go test -v" trigger this file?    its not a testing or ginkgo file. What do I miss here?
Please add doc string in the beginning of the file that explain this test file.
Do you plan to trigger it during the scripts/run_units.sh ?
</blockquote></details>

This example test file existed, so I add a new example test in this file.
Add doc string .
I don't plan to trigger it during the scripts/run_units.sh

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/181)*

**Comment by shay-berman** [comment]
LGTM

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[utils/logs/global_logger_test.go, line 3 at r3](https://reviewable.io/reviews/ibm/ubiquity/181#-LBthDmZ7DimUdnicI3b:-LDCFO8xBxqgLTgripsv:bgjjzo) ([raw file](https://github.com/ibm/ubiquity/blob/a657c1b38f089ce891ba462afdac37c9fce1e948/utils/logs/global_logger_test.go#L3)):*
<details><summary><i>Previously, hfeish (Fei Huang) wrote…</i></summary><blockquote>

This example test file existed, so I add a new example test in this file.
Add doc string .
I don't plan to trigger it during the scripts/run_units.sh
</blockquote></details>

ok so if you feel OK with this testing, then go a head and merge to dev.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/181#-:-LDCFaCNEbvSZ4F-9a1A:bb6ywmx)*

**Pull request merged**
