### PR TITLE
Added a timeout for an execute call, and a timeout for sg_inq. + unit…

### PR DESCRIPTION
**Pull request by tzurE**
…tests

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/166)

### CODE REVIEW

**Comment by shay-berman** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[utils/executor.go, line 74 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qE4hDDfeveNZ6HGaZ:-L-qE4hE_NI_MhRaQ-Nm:bb6zvpl) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L74)):*
> ```Go
> }
> 
> func (e *executor) ExecuteWithTimeout(mSeconds int ,command string, args []string) ([]byte, error) {
> ```

maybe its better to get it in seconds(i don't see us playing with miliseconds, so one line below instead of *time.Millisecond you should use *time.Second

---

*[utils/executor.go, line 80 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qDLAuYHTtyd8npHA_:-L-qDLAuYHTtyd8npHAa:b-sckfqs) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L80)):*
>  exec.CommandContext

i didn't find a way to kill it with sigKill(-9)
So we need to check if sigTerm(-15) is enough to kill the hanging sg_inq

---

*[utils/executor.go, line 86 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qBHsqPL2yRN4zwPe9:-L-qBHsqPL2yRN4zwPeA:b2b0fsy) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L86)):*
> ```Go
> 	stdErr := stderr.Bytes()
> 	stdOut := stdout.Bytes()
> 	e.logger.Debug(
> ```

Please add before this line

       exceeded_timeout=false
       timeout_happened=""
	if ctx.Err() == context.DeadlineExceeded {
                exceeded_timeout=true
		timeout_message="The command [%s] reached timeout setting [%s]msec, There for it was automatically killed"
	}
      
and please add more logs to the logs.Args as follow:
{'timeout mSeconds', mSeconds}, 
{"exceeded_timeout", exceeded_timeout}, 
{"timeout_message",timeout_message }

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/166)*

**Comment by shay-berman** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[remote/mounter/block_device_utils/mpath.go, line 168 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qFJ4_JgMra2PiTe2F:-L-qFJ4auXK2wEbaAvlc:b-278mm) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/remote/mounter/block_device_utils/mpath.go#L168)):*
> ```Go
> 	args := []string{"-p",  "0x83", dev}
> 	// add timeout in case the call never comes back.
> 	outputBytes, err := b.exec.ExecuteWithTimeout(1000, sgInqCmd, args)
> ```

1000 msec is only 1 second, I thing its too short.    change it to 5 seconds(5000)
Alon\Ran do you agree?

---

*[utils/executor.go, line 95 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qEam_0dKZSAOt6eIT:-L-qEam_0dKZSAOt6eIU:b-osaw5h) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L95)):*
> ```Go
> 		})
> 
> 	return stdOut, err
> ```

BTW i am not sure if we reach to timeout, is the Run() return error if timeout exceeded?  because if not there you have a bug here, so u need to return a specific error lets say with timeout_message 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/166)*

**Comment by ranhrl** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[utils/executor.go, line 74 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qE4hDDfeveNZ6HGaZ:-L-qEmC6FRSjFnmYBtKz:bttfqam) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L74)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

maybe its better to get it in seconds(i don't see us playing with miliseconds, so one line below instead of *time.Millisecond you should use *time.Second
</blockquote></details>

I disagree, this is a better granularity, we might reduct the timeout to less then a second in the future and also in other future reuses of this class.

---

*[utils/executor.go, line 86 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qBHsqPL2yRN4zwPe9:-L-qIZjLYAySNlQcAEC3:b-eovepm) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L86)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

Please add before this line

       exceeded_timeout=false
       timeout_happened=""
	if ctx.Err() == context.DeadlineExceeded {
                exceeded_timeout=true
		timeout_message="The command [%s] reached timeout setting [%s]msec, There for it was automatically killed"
	}
      
and please add more logs to the logs.Args as follow:
{'timeout mSeconds', mSeconds}, 
{"exceeded_timeout", exceeded_timeout}, 
{"timeout_message",timeout_message }


</blockquote></details>

I think that the proper way to do it as I found in the docs is using select:

select {
        //  		case <-ctx.Done():
        //  			return ctx.Err()
        //  		case out <- v:
        //  		}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/166)*

**Comment by ranhrl** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[utils/executor.go, line 95 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qEam_0dKZSAOt6eIT:-L-qKyacf8WaNVPF575D:b6i7ljl) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L95)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

BTW i am not sure if we reach to timeout, is the Run() return error if timeout exceeded?  because if not there you have a bug here, so u need to return a specific error lets say with timeout_message 
</blockquote></details>

Shay please look at https://golang.org/pkg/os/exec/#CommandContext

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/166)*

**Comment by ranhrl** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[utils/executor.go, line 80 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qDLAuYHTtyd8npHA_:-L-qQHO53XGhgWltvvgi:b-ol3dfb) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L80)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

>  exec.CommandContext

i didn't find a way to kill it with sigKill(-9)
So we need to check if sigTerm(-15) is enough to kill the hanging sg_inq
</blockquote></details>

it is using kill https://golang.org/pkg/os/#Process.Kill not signal

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/166)*

**Comment by ranhrl** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[remote/mounter/block_device_utils/mpath.go, line 168 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qFJ4_JgMra2PiTe2F:-L-qUQ9nKiVO2nEKwj2D:b-vics64) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/remote/mounter/block_device_utils/mpath.go#L168)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

1000 msec is only 1 second, I thing its too short.    change it to 5 seconds(5000)
Alon\Ran do you agree?
</blockquote></details>

sg_inq returns quickly if the device is attached. I guess you are afraid of iSCSI latencies? Maybe we can extend it to 2-3 seconds?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/166)*

**Comment by ranhrl** [comment]
*[utils/executor.go, line 86 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qBHsqPL2yRN4zwPe9:-L-qV3Bf4sDzu1clQVEm:buft4jl) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L86)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

I think that the proper way to do it as I found in the docs is using select:

select {
        //  		case <-ctx.Done():
        //  			return ctx.Err()
        //  		case out <- v:
        //  		}


</blockquote></details>

My mistake, just ignore this one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/166)*

**Comment by ranhrl** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/166#-:-L-qVHx7PsFnYpnaWCjQ:bnfp4nl)*

**Comment by ranhrl** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/166)*

**Comment by shay-berman** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[remote/mounter/block_device_utils/mpath.go, line 168 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qFJ4_JgMra2PiTe2F:-L-qa-_6S0ds2vFpXlzc:b-eduycf) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/remote/mounter/block_device_utils/mpath.go#L168)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

sg_inq returns quickly if the device is attached. I guess you are afraid of iSCSI latencies? Maybe we can extend it to 2-3 seconds?
</blockquote></details>

ok so the average is 4 seconds :-)
Tzur please change from 1 to 4 please.

---

*[utils/executor.go, line 80 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qDLAuYHTtyd8npHA_:-L-qbVUgZUWJyVGs_Xcs:b-a4r77o) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L80)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

it is using kill https://golang.org/pkg/os/#Process.Kill not signal
</blockquote></details>

below it send signal to the process

---

*[utils/executor.go, line 86 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qBHsqPL2yRN4zwPe9:-L-qbcfLwAt_8bltIl3W:b-ee9oac) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L86)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

My mistake, just ignore this one
</blockquote></details>

I saw this select option, its alternative, but no need to do it.

---

*[utils/executor.go, line 92 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qcdYTuHEn4cBpDxrf:-L-qcdYTuHEn4cBpDxrg:bkyq52p) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L92)):*
> ```Go
> 			{"args", args},
> 			{"error", string(stdErr[:])},
> 			{"output", string(stdOut[:])},
> ```

I see that we are not printing the error of the Run command, its not good.
Please if u already touching this, please add line 
{"exit status", err.Error()}

---

*[utils/executor.go, line 95 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qEam_0dKZSAOt6eIT:-L-qbx0B0RURqZmUTp2N:bkmxyrj) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L95)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

Shay please look at https://golang.org/pkg/os/exec/#CommandContext
</blockquote></details>

why u refering me to this link?
the question is if the timeout expired does the Run command return error?  and if so which?
I am not sure that it will return error

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/166)*

**Comment by tzurE** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[remote/mounter/block_device_utils/mpath.go, line 168 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qFJ4_JgMra2PiTe2F:-L-qtAeqepc2oAsDXOgz:b-896fix) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/remote/mounter/block_device_utils/mpath.go#L168)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

ok so the average is 4 seconds :-)
Tzur please change from 1 to 4 please.
</blockquote></details>

Done.

---

*[utils/executor.go, line 74 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qE4hDDfeveNZ6HGaZ:-L-quXQttlBt7JElpeqi:b-kyia4w) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L74)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

I disagree, this is a better granularity, we might reduct the timeout to less then a second in the future and also in other future reuses of this class.
</blockquote></details>

I agree with Ran. Also, milliseconds seems like a standard when it comes to timeouts of function calls. Lets keep it this way.

---

*[utils/executor.go, line 80 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qDLAuYHTtyd8npHA_:-L-qv7Ezhn70LY0y1RH1:bon78eq) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L80)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

below it send signal to the process
</blockquote></details>

It should work. I'll try it and tell you when I go over the logs.

---

*[utils/executor.go, line 86 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qBHsqPL2yRN4zwPe9:-L-qw1e-s-Uz4FZl8acP:b-896fix) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L86)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

I saw this select option, its alternative, but no need to do it.
</blockquote></details>

Done.

---

*[utils/executor.go, line 92 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qcdYTuHEn4cBpDxrf:-L-qwOZkzVumrTfAoM87:b-896fix) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L92)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

I see that we are not printing the error of the Run command, its not good.
Please if u already touching this, please add line 
{"exit status", err.Error()}
</blockquote></details>

Done.

---

*[utils/executor.go, line 95 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qEam_0dKZSAOt6eIT:-L-qwjTsWfc84m_D2Ejg:b-fhcq7x) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L95)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

why u refering me to this link?
the question is if the timeout expired does the Run command return error?  and if so which?
I am not sure that it will return error
</blockquote></details>

In the link you can see that in case timeout exceeded, then run returns an error. we return this error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/166)*

**Comment by ranhrl** [comment]
Review status: 2 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[utils/executor.go, line 75 at r4](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-s3NXkA2eERTPGa_kV:-L-s3NXkA2eERTPGa_kW:b-qw1zzs) ([raw file](https://github.com/ibm/ubiquity/blob/f103be60d3fa08ce489afdc30b3d922085fb497b/utils/executor.go#L75)):*
> ```Go
> 
> func (e *executor) ExecuteWithTimeout(mSeconds int ,command string, args []string) ([]byte, error) {
> 	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(mSeconds)*time.Millisecond)
> ```

What does the time.Duration doing? I don't see that they use it in the example https://golang.org/pkg/os/exec/#CommandContext

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/166)*

**Comment by ranhrl** [comment]
*[utils/executor.go, line 95 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-qEam_0dKZSAOt6eIT:-L-wcbyYBfNccKQFJTe2:b264crj) ([raw file](https://github.com/ibm/ubiquity/blob/d337b20e2e1aacf242ab8a0609f8c7d990cf9491/utils/executor.go#L95)):*
> What does the time.Duration doing? I
exactly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/166)*

**Comment by tzurE** [comment]
Review status: 2 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[utils/executor.go, line 75 at r4](https://reviewable.io:443/reviews/ibm/ubiquity/166#-L-s3NXkA2eERTPGa_kV:-L-z_bUkDNsIBSjPs-jF:bf6tv03) ([raw file](https://github.com/ibm/ubiquity/blob/f103be60d3fa08ce489afdc30b3d922085fb497b/utils/executor.go#L75)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

What does the time.Duration doing? I don't see that they use it in the example https://golang.org/pkg/os/exec/#CommandContext
</blockquote></details>

https://stackoverflow.com/questions/17573190/how-to-multiply-duration-by-integer

I saw it here.
But I also tried with 4000*time.milliseconds

could be that it's not accurate, I'm not sure actually.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/166)*

**Pull request merged**
