### PR TITLE
Propose fmt and fix typo

### PR DESCRIPTION
**Pull request by jeis2497052**
are these updates OK?

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/198)

### CODE REVIEW

**Comment by shay-berman** [comment]
Hello @jeis2497052. thanks for the PR.  Indeed, we need to do some clean up around the golang fmt.
We will consider to merge this PR later on.

**Comment by shay-berman** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/198#-:-LC-IOut7FfmQDGS91F6:bnfp4nl)*

**Comment by shay-berman** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/198)*

**Comment by beckmani** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/198#-:-LC3711wEMFwN7xPtj2o:bnfp4nl)*

**Comment by shay-berman** [comment]
this code was already changed by other PRs.    So closing it as dup.
@jeis2497052 thanks anyway.

**Pull request closed without merging**
