### PR TITLE
 #90: configurable database

### PR DESCRIPTION
**Pull request by liortamari**
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/91)

### CODE REVIEW

**Comment by shay-berman** [comment]
Review status: 0 of 15 files reviewed at latest revision, 6 unresolved discussions.

---

*[glide.yaml, line 13 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/91#-KtQzVAg31dyxQrud60R:-KtQzVAheC3u-w3w9nAi:b-5arb81) ([raw file](https://github.com/ibm/ubiquity/blob/bb8d454bf4abf84e6b27f5d3f6eca6af48b1bd00/glide.yaml#L13)):*
> ```YAML
>   subpackages:
>   - dialects/sqlite
>   - dialects/postgres
> ```

Lior please update marj about this new vendor.

---

*[database/connection.go, line 66 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/91#-KtR-5NnOG37gedq8nV_:-KtR-5NnOG37gedq8nVa:b-gtig2n) ([raw file](https://github.com/ibm/ubiquity/blob/bb8d454bf4abf84e6b27f5d3f6eca6af48b1bd00/database/connection.go#L66)):*
> ```Go
> 
> func (f *postgresFactory) newConnection() (*gorm.DB, error) {
>     return gorm.Open("postgres", fmt.Sprintf("host=%s user=postgres dbname=postgres sslmode=disable", f.host))
> ```

1. user should not be hardcoded (get it as param), also the dbname.
2. please also add password

---

*[database/connection_test.go, line 45 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/91#-KtR-r158ucd9S9snTm2:-KtR-r158ucd9S9snTm3:b7rajj9) ([raw file](https://github.com/ibm/ubiquity/blob/bb8d454bf4abf84e6b27f5d3f6eca6af48b1bd00/database/connection_test.go#L45)):*
> ```Go
>             Expect(pgsql.GetDb()).To(BeNil())
>         })
>         It("open fail", func() {
> ```

Please add some test about wrong password.  (not certificate, just the basic user and password validation)

---

*[local/scbe/datamodel.go, line 61 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/91#-KtR0UAi22DHirevki92:-KtR0UAi22DHirevki93:b-sza5gm) ([raw file](https://github.com/ibm/ubiquity/blob/bb8d454bf4abf84e6b27f5d3f6eca6af48b1bd00/local/scbe/datamodel.go#L61)):*
> ```Go
> 	defer d.logger.Trace(logs.DEBUG)()
> 
> 	if err := d.database.AutoMigrate(&resources.Volume{}).Error; err != nil {
> ```

explain why you add it here?  (where it comes from)

---

*[resources/resources.go, line 76 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/91#-KtR1NUedBqZIVrE2GfL:-KtR1NUedBqZIVrE2GfM:b-ojslxr) ([raw file](https://github.com/ibm/ubiquity/blob/bb8d454bf4abf84e6b27f5d3f6eca6af48b1bd00/resources/resources.go#L76)):*
> ```Go
> const PathToMountUbiquityBlockDevices = "/ubiquity/%s"    // %s is the WWN of the volume # TODO this should be moved to docker plugin side
> const OptionNameForVolumeFsType = "fstype"                // the option name of the fstype and also the key in the volumeConfig
> const DatabseSuffix = "ibm-ubiquity-db"
> ```

semantic - DatabaseVolumeNameSuffix

---

*[web_server/storage_api_handler.go, line 338 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/91#-KtR1maSJ0cKvHBRshDr:-KtR1maSJ0cKvHBRshDs:b-22vlbu) ([raw file](https://github.com/ibm/ubiquity/blob/bb8d454bf4abf84e6b27f5d3f6eca6af48b1bd00/web_server/storage_api_handler.go#L338)):*
> ```Go
> 	if err = dbConnection.Open(); err != nil {
> 		backendName = h.config.DefaultBackend
> 		h.logger.Printf("no db connection, going to DefaultBackend %s", backendName)
> ```

maybe its better to log it as warning level instead of debug ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/91)*

**Comment by liortamari** [comment]
Review status: 0 of 15 files reviewed at latest revision, 6 unresolved discussions.

---

*[database/connection.go, line 66 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/91#-KtR-5NnOG37gedq8nV_:-KtRSECBoEHAvr-Jc7z2:b90frvu) ([raw file](https://github.com/ibm/ubiquity/blob/bb8d454bf4abf84e6b27f5d3f6eca6af48b1bd00/database/connection.go#L66)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

1. user should not be hardcoded (get it as param), also the dbname.
2. please also add password
</blockquote></details>

1. i do not see the value in changing the username and dbname
2. password will be added later when we configure postgres with security

---

*[database/connection_test.go, line 45 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/91#-KtR-r158ucd9S9snTm2:-KtRTDsh1Iw-rfQf_UTp:b-2ow18o) ([raw file](https://github.com/ibm/ubiquity/blob/bb8d454bf4abf84e6b27f5d3f6eca6af48b1bd00/database/connection_test.go#L45)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

Please add some test about wrong password.  (not certificate, just the basic user and password validation)
</blockquote></details>

i dont see how.  you'll need to setup posgres test server for that

---

*[resources/resources.go, line 76 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/91#-KtR1NUedBqZIVrE2GfL:-KtRT9teCfSt_w1BcbnV:b32wtd) ([raw file](https://github.com/ibm/ubiquity/blob/bb8d454bf4abf84e6b27f5d3f6eca6af48b1bd00/resources/resources.go#L76)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

semantic - DatabaseVolumeNameSuffix
</blockquote></details>

ok

---

*[web_server/storage_api_handler.go, line 338 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/91#-KtR1maSJ0cKvHBRshDr:-KtRT2eWvEMUUl_Znx9u:b-v1x2t1) ([raw file](https://github.com/ibm/ubiquity/blob/bb8d454bf4abf84e6b27f5d3f6eca6af48b1bd00/web_server/storage_api_handler.go#L338)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

maybe its better to log it as warning level instead of debug ?
</blockquote></details>

yes mabye, but we don't have our new logger here, its the old one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/91)*

**Comment by liortamari** [comment]
Review status: 0 of 15 files reviewed at latest revision, 6 unresolved discussions.

---

*[local/scbe/datamodel.go, line 61 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/91#-KtR0UAi22DHirevki92:-KtRYkYS8pKy4GnXiDOe:b-o8e9ex) ([raw file](https://github.com/ibm/ubiquity/blob/bb8d454bf4abf84e6b27f5d3f6eca6af48b1bd00/local/scbe/datamodel.go#L61)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

explain why you add it here?  (where it comes from)
</blockquote></details>

i will find a better place for it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/91)*

**Comment by shay-berman** [comment]
Review status: 0 of 15 files reviewed at latest revision, 12 unresolved discussions.

---

*[main.go, line 99 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/91#-KtW6OwMd16JbY8vE3sP:-KtW6OwMd16JbY8vE3sQ:bt6s3sg) ([raw file](https://github.com/ibm/ubiquity/blob/bb8d454bf4abf84e6b27f5d3f6eca6af48b1bd00/main.go#L99)):*
> ```Go
> 	}
> 
> 	defer database.InitSqlite(path.Join(ubiquityConfigPath, "ubiquity.db"))()
> ```

why u still init sqlite by default?   maybe we can do it only if ssc backend is configured?

---

*[local/scbe/datamodel_wrapper.go, line 49 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/91#-KtVt9VUGazSfJi-EOOI:-KtVt9VVBR8anhJz6jSV:b-4mjk2z) ([raw file](https://github.com/ibm/ubiquity/blob/bb8d454bf4abf84e6b27f5d3f6eca6af48b1bd00/local/scbe/datamodel_wrapper.go#L49)):*
> ```Go
> func isDatabaseVolume(volName string) bool {
> 	defer logs.GetLogger().Trace(logs.DEBUG)()
> 	isDatabaseVolume := strings.HasSuffix(volName, resources.DatabseSuffix)
> ```

this could be an issue
if u have 2 ubiquitys that uses the same pool/service then one can use the other db vol because u just check the suffix.

---

*[local/scbe/datamodel_wrapper.go, line 122 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/91#-KtVsVcoeBeB88WJG8n1:-KtVsVcoeBeB88WJG8n2:bvgh6zs) ([raw file](https://github.com/ibm/ubiquity/blob/bb8d454bf4abf84e6b27f5d3f6eca6af48b1bd00/local/scbe/datamodel_wrapper.go#L122)):*
> ```Go
> 	}
> 
> 	// verify existence
> ```

a bit confusing.
maybe should be out side of this function, like verify_existance()
just a suggestion

---

*[local/scbe/datamodel_wrapper.go, line 143 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/91#-KtTAUOm1ev24mR3Prti:-KtTAUOm1ev24mR3Prtj:b3ine50) ([raw file](https://github.com/ibm/ubiquity/blob/bb8d454bf4abf84e6b27f5d3f6eca6af48b1bd00/local/scbe/datamodel_wrapper.go#L143)):*
> ```Go
> 		// sanity
> 		if d.dbVolume == nil {
> 			return d.logger.ErrorRet(&volumeNotFoundError{name}, "failed")
> ```

volumenotfounderror  maybe better to change for specific db vol not found

---

*[local/scbe/datamodel_wrapper.go, line 156 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/91#-KtVxOWtZiLRhcgm_T4S:-KtVxOWtZiLRhcgm_T4T:b-qhpe8d) ([raw file](https://github.com/ibm/ubiquity/blob/bb8d454bf4abf84e6b27f5d3f6eca6af48b1bd00/local/scbe/datamodel_wrapper.go#L156)):*
> // open db connection
> 		dbConnection := database.NewConnection()
> 		if err = dbConnection.Open(); err != nil {
> 			return d.logger.ErrorRet(err, "dbConnection.Open failed")
> 		}
> 		defer dbConnection.Close()

looks like we repeat this on all functions, maybe some refactoring to make it generic?

also the createTableIfNeeded repeat all the time, just wonder if we can do it in generic way.

---

*[local/scbe/datamodel_wrapper_test.go, line 81 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/91#-KtW1jrGBSIEwZwMjoFm:-KtW1jrGBSIEwZwMjoFn:b5yb92i) ([raw file](https://github.com/ibm/ubiquity/blob/bb8d454bf4abf84e6b27f5d3f6eca6af48b1bd00/local/scbe/datamodel_wrapper_test.go#L81)):*
> ```Go
>             })
>             It("fail for non db volume", func() {
>                 sqliteDbCloseFunc := database.InitSqlite(sqliteDbPath)
> ```

why you need to initSqlite?  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/91)*

**Comment by shay-berman** [comment]
Reviewed 13 of 15 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/91)*

**Pull request closed without merging**
