### PR TITLE
Containerized ubiquity #89

### PR DESCRIPTION
**Pull request by midoblgsm**
This adds docker file for ubiquity and deployment files for ubiquity, postgres and ingress

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/95)

### CODE REVIEW

**Comment by shay-berman** [comment]
Review status: 0 of 21 files reviewed at latest revision, 7 unresolved discussions.

---

*[Dockerfile, line 9 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtYBaENqh0yUX9JjFm8:-KtYBaENqh0yUX9JjFm9:b41zget) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/Dockerfile#L9)):*
> ```Dockerfile
> 
> 
> FROM alpine:latest
> ```

explicit is better than implisit

use specific alpine version

---

*[Dockerfile, line 12 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtYBjGQ6IAg3cvYc-6v:-KtYBjGQ6IAg3cvYc-6w:bbxefru) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/Dockerfile#L12)):*
> ```Dockerfile
> RUN apk --no-cache add ca-certificates
> WORKDIR /root/
> RUN mkdir -p /tmp/ubiquity
> ```

i think the best practic is not to run it as root
so maybe better just to add ubiquity user to the image and just run it from ubiquity user.

root container is less common

---

*[ubiquity-server.conf, line 1 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtYCA7BFMyvsVCLW-jg:-KtYCA7CzMBeGr3MYzwA:b-hmsgcb) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/ubiquity-server.conf#L1)):*
> ```
> port = 9999               # Ubiquity port
> ```

maybe better to change this file to bash
and instead key = val
lets do

export key=val
so it will be ready for the new form of envs 

---

*[deploy/ingress/default-backend.yaml, line 17 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtYCqT_cAdge0qAVrbH:-KtYCqT_cAdge0qAVrbI:b-ys95dl) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/ingress/default-backend.yaml#L17)):*
> ```YAML
>       terminationGracePeriodSeconds: 60
>       containers:
>       - name: default-http-backend
> ```

not sure about this 
maybe add more comments to explain the need

---

*[deploy/ingress/default-backend.yaml, line 21 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtYD4vJgxAxA9lrOurS:-KtYD4vK6pir_bEQFNyR:bta9j5z) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/ingress/default-backend.yaml#L21)):*
> ```YAML
>         # 1. It serves a 404 page at /
>         # 2. It serves 200 on a /healthz endpoint
>         image: gcr.io/google_containers/defaultbackend:1.0
> ```

this may need some legal to use?
we should consult marj here

---

*[deploy/ingress/nginx-tcp-ingress-controller.yaml, line 35 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtYDRrZfupSL-RFgzO6:-KtYDRrZfupSL-RFgzO7:bm9wam8) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/ingress/nginx-tcp-ingress-controller.yaml#L35)):*
> ```YAML
>           timeoutSeconds: 1
>         env:
>           - name: POD_NAME
> ```

add comments please
what is it

not sure i understand this yml

---

*[deploy/postgres/replica-service.json, line 1 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtYDn8GaDH3CJEZp683:-KtYDn8HAzJx1SAndNmP:b-q7wex6) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/postgres/replica-service.json#L1)):*
> ```JSON
> {
> ```

is posible add some comments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/95)*

**Comment by shay-berman** [comment]
Review status: 0 of 21 files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtYE5zWdPWOCNSZXpj6:-KtYE5zXvFsESZFLNPTY:b-8utfel) (no related file):*
conducted partial review to give you quick feedback
will continue to review on sunday

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/95)*

**Comment by aswarke** [comment]
Review status: 0 of 21 files reviewed at latest revision, 8 unresolved discussions.

---

*[Dockerfile, line 12 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtYBjGQ6IAg3cvYc-6v:-KtYPzHJBXg6Yx1VYb9G:btsyycj) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/Dockerfile#L12)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

i think the best practic is not to run it as root
so maybe better just to add ubiquity user to the image and just run it from ubiquity user.

root container is less common
</blockquote></details>

@shay-berman root in container is NOT the same as root on Host.  Ubiquity Docker Plugin, Flex , Provisioner and Ubiquity Service will be running as root inside container. It is not recommended to use sudo inside container and running privileged commands. See https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#user .  Creating a non-root user and then running with sudo ( root ) permissions doesn't make sense when root in container is not the same as that on the host .  We have removed sudo operations from the codebase as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/95)*

**Comment by shay-berman** [comment]
Review status: 0 of 21 files reviewed at latest revision, 8 unresolved discussions.

---

*[Dockerfile, line 12 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtYBjGQ6IAg3cvYc-6v:-Kt_TKSvWIIsr8sVY31-:b3lgy2h) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/Dockerfile#L12)):*
<details><summary><i>Previously, aswarke (Amit Warke) wrote…</i></summary><blockquote>

@shay-berman root in container is NOT the same as root on Host.  Ubiquity Docker Plugin, Flex , Provisioner and Ubiquity Service will be running as root inside container. It is not recommended to use sudo inside container and running privileged commands. See https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#user .  Creating a non-root user and then running with sudo ( root ) permissions doesn't make sense when root in container is not the same as that on the host .  We have removed sudo operations from the codebase as well
</blockquote></details>

i agree with all your comment.
but i didnt talk about flex nor docker plugin, of cause both should run as root inside tge container.

this comment is about ubiquity server container only.     do u see any reason why ubiquity server should run as root?    btw the same for the provisioner.      

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/95)*

**Comment by shay-berman** [comment]
Review status: 0 of 21 files reviewed at latest revision, 15 unresolved discussions.

---

*[deploy/ubiquity/ubiquity_deployment.yml, line 3 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KteX_hjS9EcbYh5GYBW:-KteX_hkIlUHPZ_FuFb3:b-carpnp) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/ubiquity/ubiquity_deployment.yml#L3)):*
> ```YAML
> ---
> apiVersion: v1
> kind: Service
> ```

I believe we should split the service to a different file because it may be created not at the same time.

---

*[deploy/ubiquity/ubiquity_deployment.yml, line 36 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtedYWRbE_KwiFXMbQk:-KtedYWRbE_KwiFXMbQl:b-ntgb7h) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/ubiquity/ubiquity_deployment.yml#L36)):*
> ```YAML
>         - containerPort: 9999
>           name: ubiquity-port
>         env:
> ```

i think all of this env should be a configMAP that will be define by the user, so we can have a generic deployment and get the ubiqutiy configMAP,

---

*[deploy/ubiquity/ubiquity_deployment.yml, line 39 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-Kteg9ujgdYRUGmnOaj4:-Kteg9ujgdYRUGmnOaj5:b-ka45eu) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/ubiquity/ubiquity_deployment.yml#L39)):*
> ```YAML
>           - name: PORT             # Ubiquity port
>             value: "9999"
>           - name: LOG_PATH         # Ubiquity log file directory
> ```

about log file
i wonder what is the standard here.
do we want to stay with logging to file, or we should log everything to STDout, so customer will be able just to do 
docker log container  (or the k8s referance) to see the logs
or we really want to keep the log file, and if so then we need to keep the log file in a volume directory.

What do you say?

---

*[deploy/ubiquity/ubiquity_deployment.yml, line 41 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtefdkXdgtu9bTIrIla:-KtefdkXdgtu9bTIrIlb:b-sqm5by) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/ubiquity/ubiquity_deployment.yml#L41)):*
> ```YAML
>           - name: LOG_PATH         # Ubiquity log file directory
>             value: "/tmp"
>           - name: CONFIG_PATH         # Ubiquity config directory
> ```

R u sure we need CONFIG_PATH?

---

*[deploy/ubiquity/ubiquity_deployment.yml, line 58 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KteXB72xL4tveNu-XyI:-KteXB72xL4tveNu-XyJ:b69dtje) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/ubiquity/ubiquity_deployment.yml#L58)):*
> LT_FILESYSTEM_NAME
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>
>             value: "gold"
>             #This variable is needed just in case of spectrum scale nfs backend
>           - name: SSC_NFS_SERVER_ADDRESS
>             value: "127.0.0.1"
>             #The SSC_SSH_* variables are needed in cas of using ssh with spectrum scale
>           - name: SSC_SSH_HOST
>             value: "192.168.10.10"
>           - name: SSC_SSH_PORT
>             value: "22"
>           - name: SSC_SSH_USER
>             value: "ubiquity"
</details>

also this problematic , its only SSc.
as the comment below we may need some install that will generic the relevant deployment.
at least for the GA i will setup config files only for SCBE.   What do you think?

---

*[deploy/ubiquity/ubiquity_deployment.yml, line 70 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KteXm69f63msDg3aV4_:-KteXm69f63msDg3aV4a:b4aixco) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/ubiquity/ubiquity_deployment.yml#L70)):*
> ```YAML
>           - name: DEFAULT_FSTYPE
>             value: "ext4"
>           - name: SCBE_MANAGEMENT_IP
> ```

missing ubiquity DB IP env.  (the serviceIP of the ubiquityDB)
the ubiquity new DB is already inside the dev branch.

---

*[deploy/ubiquity/ubiquity_deployment.yml, line 80 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KteWEz2P3FPm3wKX09Q:-KteWEz2P3FPm3wKX09R:b-1r2737) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/ubiquity/ubiquity_deployment.yml#L80)):*
> ```YAML
>           - name: SCBE_PASSWORD
>             value: "PASSWORD"
>         #This volume is needed just for spectrum scale backend
> ```

This is problematic since its only for SSc

I believe that the installer should question if its SSc then he will add this section to the yml on the fly, otherwise it should be out by default.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/95)*

**Comment by shay-berman** [comment]
Review status: 0 of 21 files reviewed at latest revision, 20 unresolved discussions.

---

*[ubiquity-server.conf, line 1 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtYCA7BFMyvsVCLW-jg:-Ktj_noqI9iAL1SzslPb:b-puewbh) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/ubiquity-server.conf#L1)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

maybe better to change this file to bash
and instead key = val
lets do

export key=val
so it will be ready for the new form of envs 
</blockquote></details>

sorry its not a good idea (change it to export)
we just need to make sure this file can be an input to kubectl create configmap, if so then its enough.  No need to make it with export

---

*[deploy/postgres/master-service.json, line 2 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtjmtW8NRS8haZNyyp9:-KtjmtWAXwql4C0duTPq:b-3mvwfq) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/postgres/master-service.json#L2)):*
> ```JSON
> {
>         "kind": "Service",
> ```

any special reason why its json and not yml?   is it because you copy it from a source?

---

*[deploy/postgres/set.json, line 24 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtjfwEKBiRdFdJO6UWX:-KtjfwELpSfwJ2ca7ZeO:b-x3fm7n) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/postgres/set.json#L24)):*
> ```JSON
>                 "containers": [{
>                     "name": "pgset",
>                     "image": "crunchydata/crunchy-postgres:centos7-9.6-1.5.1",
> ```

why this specific image?

---

*[deploy/postgres/set.json, line 39 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-Ktjg6xuxDw8nGMD9in-:-Ktjg6xuxDw8nGMD9in0:bg9cfrg) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/postgres/set.json#L39)):*
> ```JSON
>                         "value": "set"
>                     }, {
>                         "name": "PG_MASTER_HOST",
> ```

what is master node?
its only 1 PG node

---

*[deploy/postgres/set.json, line 62 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtjgLE9qQyNEFWIvlpy:-KtjgLE9qQyNEFWIvlpz:b7k089z) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/postgres/set.json#L62)):*
> ```JSON
>                     "volumeMounts": [{
>                         "name": "pgdata",
>                         "mountPath": "/pgdata",
> ```

is this work for you?
because PG need its data inside /var/lib/postgresql/data directory

---

*[deploy/ubiquity/ubiquity_deployment.yml, line 20 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-Ktjl9H5hKstGDgYCQUg:-Ktjl9H5hKstGDgYCQUh:b5afgyg) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/ubiquity/ubiquity_deployment.yml#L20)):*
> ```YAML
> kind: Deployment
> metadata:
>   name: ubiquity
> ```

is missing
namespace: ubiquity 

actually should be in all the ymls.
Do you agree?

---

*[deploy/ubiquity/ubiquity_deployment.yml, line 36 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtedYWRbE_KwiFXMbQk:-Ktjiy9HEzOxhkJw50xi:b-6ytb0k) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/ubiquity/ubiquity_deployment.yml#L36)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

i think all of this env should be a configMAP that will be define by the user, so we can have a generic deployment and get the ubiqutiy configMAP,
</blockquote></details>

so instead of :
- name: PORT
  value: "9999"

it should be 
- name: PORT
    valueFrom:
        configMapRef:
            name: ubiquity-config
            key: PORT

So all the configs will go to configmap named : ubiquity-config  

ubiquity-config.yml
====================
apiVersion: v1
kinnd: ConfigMap
metadata:
   name : ubiquity-config
   namespace: ubiquity
data:
    PORT=9999

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/95)*

**Comment by shay-berman** [comment]
Review status: 0 of 24 files reviewed at latest revision, 21 unresolved discussions.

---

*[Dockerfile, line 1 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/95#-Ktq2n22tMGGf405gZWf:-Ktq2n22tMGGf405gZWg:b-glal6l) ([raw file](https://github.com/ibm/ubiquity/blob/949597fa991cf94b176885c728b22fa16d789513/Dockerfile#L1)):*
> ```Dockerfile
> FROM golang:1.7.3
> ```

Why do we use 1.7.3?

there is already 1.9 available why not to use it -> https://golang.org/doc/devel/release.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/95)*

**Comment by shay-berman** [comment]
Review status: 0 of 24 files reviewed at latest revision, 23 unresolved discussions.

---

*[deploy/postgres/set.json, line 3 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtqQTU6tlhM7igCD6q_:-KtqQTU6tlhM7igCD6qa:b-sedgmh) ([raw file](https://github.com/ibm/ubiquity/blob/949597fa991cf94b176885c728b22fa16d789513/deploy/postgres/set.json#L3)):*
> ```JSON
> {
>     "apiVersion": "apps/v1beta1",
>     "kind": "StatefulSet",
> ```

Why stateful set?
Actually if you are using stateful set but only with replica=1 then there is no meaning for stateful set.
instead we can just use Deployment.

The only reason to use stateful set is if we set the postgress in cluster mode, but we don't have any plans to do so for first GA.

In addition below you mentioned persistentVolumeClaim, BUT there is no PVC in stateful set. there is only   volumeClaimTemplates.

---

*[deploy/postgres/set.json, line 68 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtqTlXhzR1birycGA2r:-KtqTlXhzR1birycGA2s:blnh9ls) ([raw file](https://github.com/ibm/ubiquity/blob/949597fa991cf94b176885c728b22fa16d789513/deploy/postgres/set.json#L68)):*
> ```JSON
>                 "volumes": [{
>                     "name": "pgdata",
>                     "persistentVolumeClaim": {
> ```

this is not posible in stateful-set

https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/95)*

**Comment by shay-berman** [comment]
Review status: 0 of 22 files reviewed at latest revision, 16 unresolved discussions.

---

*[deploy/postgres/set.json, line 24 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtjfwEKBiRdFdJO6UWX:-KuFzIy8OGWp2sp5bfUt:bn1hb98) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/postgres/set.json#L24)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

why this specific image?
</blockquote></details>

not relevant, we will deliver dedicated PG image with securty

---

*[deploy/postgres/set.json, line 3 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KtqQTU6tlhM7igCD6q_:-KuFzBy0PlXC3cp31hK8:b5sums3) ([raw file](https://github.com/ibm/ubiquity/blob/949597fa991cf94b176885c728b22fa16d789513/deploy/postgres/set.json#L3)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

Why stateful set?
Actually if you are using stateful set but only with replica=1 then there is no meaning for stateful set.
instead we can just use Deployment.

The only reason to use stateful set is if we set the postgress in cluster mode, but we don't have any plans to do so for first GA.

In addition below you mentioned persistentVolumeClaim, BUT there is no PVC in stateful set. there is only   volumeClaimTemplates.

</blockquote></details>

so we agree that no need for stateful set only deployment.

---

*[deploy/ubiquity/ubiquity_deployment.yml, line 3 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KteX_hjS9EcbYh5GYBW:-KuFz_HcPNytpUG7GiQb:bb7f2mf) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/ubiquity/ubiquity_deployment.yml#L3)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

I believe we should split the service to a different file because it may be created not at the same time.
</blockquote></details>

done

---

*[deploy/ubiquity/ubiquity_deployment.yml, line 20 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-Ktjl9H5hKstGDgYCQUg:-KuFzXazGzaLWlfHG3fJ:bkdhis1) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/ubiquity/ubiquity_deployment.yml#L20)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

is missing
namespace: ubiquity 

actually should be in all the ymls.
Do you agree?
</blockquote></details>

i will add name space later on

---

*[deploy/ubiquity/ubiquity_deployment.yml, line 39 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/95#-Kteg9ujgdYRUGmnOaj4:-KuFzdjP7KmwDVgOdBWQ:b-ly3bux) ([raw file](https://github.com/ibm/ubiquity/blob/15159ab4b7397de866235257a072136aca119b59/deploy/ubiquity/ubiquity_deployment.yml#L39)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

about log file
i wonder what is the standard here.
do we want to stay with logging to file, or we should log everything to STDout, so customer will be able just to do 
docker log container  (or the k8s referance) to see the logs
or we really want to keep the log file, and if so then we need to keep the log file in a volume directory.

What do you say?
</blockquote></details>

I opened ticket about it

---

*[remote/mounter/block_device_utils/mpath.go, line 84 at r5](https://reviewable.io:443/reviews/ibm/ubiquity/95#-KuG3RuYd6vZQYM5FUej:-KuG3RuZoDuz1Lb_DB22:b-ockxk5) ([raw file](https://github.com/ibm/ubiquity/blob/c11594947065a73f547c4a251c4a415753fcc4a1/remote/mounter/block_device_utils/mpath.go#L84)):*
> CONFIG_PATH
This is not really related to the containerized ubiquity server.
because its run in the docker plugin or flex.
if u change this we must say the customer to install flex as root user (without option for sudo). I am OK with it but is this what you intended to do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/95)*

**Comment by shay-berman** [comment]
Reviewed 12 of 21 files at r1, 2 of 4 files at r2, 2 of 4 files at r5, 2 of 4 files at r6, 8 of 8 files at r7, 1 of 1 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/95)*

**Pull request merged**
