### PR TITLE
 #107 - create image for secured postgresql

### PR DESCRIPTION
**Pull request by ranhrl**
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/108)

### CODE REVIEW

**Comment by shay-berman** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[scripts/ubiquity-postgresql/Dockerfile, line 1 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-Ku0Kh6nmi_7RuUwH1aP:-Ku0Kh6oFsuox_7_LJs-:b-7ai7x8) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/Dockerfile#L1)):*
> ```Dockerfile
> FROM postgres:9.6
> ```

please tell marj about this specifc postgress version

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh, line 1 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-KuDQ_OfxqYUNkxPbjTm:-KuDQ_OfxqYUNkxPbjTn:b-wj0rcx) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

please add doc string that explain what this script do.

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh, line 4 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-Ku0KzBXSp0kNFgDPkyU:-Ku0KzBYPlm2eGFSkndc:bmw6vfu) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh#L4)):*
> ```Shell
> set -e
> 
> echo "Configuring Postgres for SSL!";
> ```

please remove the ; at the end  (also in other places below. in bash u don't need ;  end of the line)

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh, line 7 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-Ku0LRROuLgLcty4TAXd:-Ku0LRROuLgLcty4TAXe:bxo9kqi) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh#L7)):*
> ```Shell
> 
> if [ -z "$POSTGRES_USER" ]; then
>   export POSTGRES_USER="postgres";
> ```

please put it as 'const' at the top of the file (so it will be easier to change it in needed later on without dig the code). 

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh, line 11 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-Ku0LCunxqI_39eeFjRY:-Ku0LCuoyOmhgjAUVJ5a:bizucqq) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh#L11)):*
> ```Shell
> 
> if [ -z "$POSTGRES_EMAIL" ]; then
>   export POSTGRES_EMAIL="user@test.com";
> ```

what is this?
is it ok to put dammi here?  

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh, line 14 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-Ku0NWxM6OZePELUrivV:-Ku0NWxM6OZePELUrivW:bqn8wy1) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh#L14)):*
> ```Shell
> fi
> 
> export SSLDIR="/var/lib/postgresql/ssl"
> ```

1. please put at the top of the file all the envs including this 
2. validate that we don't have a problem to locate the ssl dir inside the directory that is persistence for the DB.

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh, line 25 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-Ku0NE04XYybCPJgxAfl:-Ku0NE04XYybCPJgxAfm:b-nvh0nq) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh#L25)):*
> ```Shell
>     # Create SSL directory
>     mkdir $SSLDIR
>     chown postgres.postgres $SSLDIR
> ```

postgres.postgres   strange syntax , please change to the standard way postgres:postgres

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh, line 31 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-KuDQ3dBWqqnU2jmwX8C:-KuDQ3dBWqqnU2jmwX8D:bp55f8r) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh#L31)):*
> ```Shell
> cd $SSLDIR
> 
> if [ ! -s "$SSLDIR/server.crt" ]
> ```

is this the only file you need to check if its exist?
make sure you are not overwrite customer keys.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/108)*

**Comment by alonm** [comment]
Review status: 0 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[scripts/ubiquity-postgresql/Dockerfile, line 1 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-Ku0Kh6nmi_7RuUwH1aP:-KuDTQp6asIHkHoMwkBQ:bgyun97) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/Dockerfile#L1)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

please tell marj about this specifc postgress version
</blockquote></details>

In SCB we use 9.2. Is there a reason for this difference? Do we have a reason to update SCB as well?

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh, line 19 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-KuDSRZK-7hYKSF4GEWQ:-KuDSRZK-7hYKSF4GEWR:bsyi57f) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh#L19)):*
> ```Shell
> head -n -1 /var/lib/postgresql/data/pg_hba.conf > /tmp/pg_hba.conf
> echo "hostssl all all all password" >> /tmp/pg_hba.conf
> mv /tmp/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf
> ```

Why use a tmp file? Why not do the manipulation directly to the correct path?
The file names should also be moved to the be const at the top of the file.

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-user-db.sh, line 6 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-KuDUJNBZQEpOySaZKyh:-KuDUJNCR3ouFnO1oOCj:b-lzh50j) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-user-db.sh#L6)):*
> ```Shell
> echo "Creating user for ubiquity.."
> 
> psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
> ```

What if user/database already exist?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/108)*

**Comment by alonm** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/108)*

**Comment by ranhrl** [comment]
Review status: 1 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh, line 7 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-Ku0LRROuLgLcty4TAXd:-KuDuZkojI69tb4NBOAm:b-6g442) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh#L7)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

please put it as 'const' at the top of the file (so it will be easier to change it in needed later on without dig the code). 
</blockquote></details>

It is the top...

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh, line 11 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-Ku0LCunxqI_39eeFjRY:-KuDvLV6r2LbUOf-3dWB:b-5q93tf) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh#L11)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

what is this?
is it ok to put dammi here?  
</blockquote></details>

It's for the certificate email address, what do you have in mind? ...

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh, line 14 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-Ku0NWxM6OZePELUrivV:-KuDvfNFe7Ac6w0cL29M:bcz7kms) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh#L14)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

1. please put at the top of the file all the envs including this 
2. validate that we don't have a problem to locate the ssl dir inside the directory that is persistence for the DB.
</blockquote></details>

Dude, it is the top...

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh, line 19 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-KuDSRZK-7hYKSF4GEWQ:-KuDwWfnlRulDNm9rFWr:b-yv2huy) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh#L19)):*
<details><summary><i>Previously, alonm wrote…</i></summary><blockquote>

Why use a tmp file? Why not do the manipulation directly to the correct path?
The file names should also be moved to the be const at the top of the file.
</blockquote></details>

Usually you do that so the last copy is a one step so you don't get half work done in case something goes wrong in the middle.

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh, line 31 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-KuDQ3dBWqqnU2jmwX8C:-KuE4ttnWtLvQZTmbKjT:b2via7q) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh#L31)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

is this the only file you need to check if its exist?
make sure you are not overwrite customer keys.
</blockquote></details>

let's discuss it face to face

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/108)*

**Comment by ranhrl** [comment]
Review status: 1 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[scripts/ubiquity-postgresql/Dockerfile, line 1 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-Ku0Kh6nmi_7RuUwH1aP:-KuE8ouwX1zbCSsWjuzz:b-y2ajbb) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/Dockerfile#L1)):*
<details><summary><i>Previously, alonm wrote…</i></summary><blockquote>

In SCB we use 9.2. Is there a reason for this difference? Do we have a reason to update SCB as well?
</blockquote></details>

it's always better to run the latest stable version if you have no reason against it.

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-user-db.sh, line 6 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-KuDUJNBZQEpOySaZKyh:-KuE93uocWT0e8CeXOnF:b-w0bta9) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-user-db.sh#L6)):*
<details><summary><i>Previously, alonm wrote…</i></summary><blockquote>

What if user/database already exist?
</blockquote></details>

Then nothing will happen

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/108)*

**Comment by shay-berman** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh, line 11 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-Ku0LCunxqI_39eeFjRY:-KuEz9vCBsL1ZoKI3X7B:b-5tuf2x) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh#L11)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

It's for the certificate email address, what do you have in mind? ...
</blockquote></details>

so do you plan to keep this dummy email?

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh, line 14 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/108#-Ku0NWxM6OZePELUrivV:-KuEzKOsBgA0-abn-uQ5:bccw1nu) ([raw file](https://github.com/ibm/ubiquity/blob/4d583ca46712a48d27db6e52d5216104e2dcbc88/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh#L14)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

Dude, it is the top...
</blockquote></details>


Is there a problem to locate the ssl dir inside the directory of the PV?  Did you try it?  (its a mount inside a mount point not sure if its ok)

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-user-db.sh, line 7 at r2](https://reviewable.io:443/reviews/ibm/ubiquity/108#-KuF-Ak5YOMZMyq9U2FU:-KuF-Ak5YOMZMyq9U2FV:bnwqxfo) ([raw file](https://github.com/ibm/ubiquity/blob/a9b1e4a0dc35bc532a2d2cd49ff50301cac03c28/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-user-db.sh#L7)):*
> ```Shell
> 
> psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
>     CREATE USER ubiquity;
> ```

yes, now i see that the user and password is hardcoded.   as we discussed this should be change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/108)*

**Comment by shay-berman** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/108#-:-KuG8Iu9CEeQJBjSyoWB:bnfp4nl)*

**Pull request merged**
