### PR TITLE
Fix/mount idempotent improvements

### PR DESCRIPTION
**Pull request by shay-berman**
This PR in conjunction with https://github.com/IBM/ubiquity-k8s/pull/177 (it provides some mounter side facilities to be used in the ubiquity-k8s flex side to address flex side idempotent aspects)

This PR introduce the following:
1. **fixes idempotent issues in the MountDeviceFlow**:
1.1. Skip mount if already mounted to the right mountpoint. (refactor IsDeviceMounted to return also the mountpoints of the mounted device)
1.2. If mounted to wrong mountpoint it should fail. 
(note: set 20second timeout for identify if its already mounted)

2. **Add timeout to "mount" command** executions to prevent any potential hanging during the mount command. 2.1. mount to identify if device is mounted - timeout set to 20seconds.  
2.2. mount for actually mounting device set timeout to 2 minutes.

3. **New interface mounter_factory.go** [ubiquity/remote/mounter/mounter_factory.go] to get the relevant remote backend by backend name.  
(used by ubiquity-k8s/controller/controller.go)

4. Add new methods to the **Executer interface : Lstat, IsDir, Symlink, IsSlink**.  
(used by ubiquity-k8s/controller/controller.go to handle idempotent aspects in the flex mount side of thing)

5. **Full unit testing coverage** to all the items above.

6. Added few TODO lines for potential Idempotent items to improve in the umount flow.

**How to test**
Simulate the relevant idempotent issue in the mount flow, Including hanging mount commands to validate the timeouts as well.

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/196)

### CODE REVIEW

**Comment by shay-berman** [comment]
Passed ubiquity sanity (with both this PR and https://github.com/IBM/ubiquity-k8s/pull/177)

**Comment by tzurE** [comment]
Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[remote/mounter/mounter_factory.go, line 35 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/196#-L8S_NxDDjTi_i30FVA3:-L8S_NxDDjTi_i30FVA4:b-jft6n4) ([raw file](https://github.com/ibm/ubiquity/blob/019bdfe0c4fbdecd81ae51ddba64f6c51f35f90d/remote/mounter/mounter_factory.go#L35)):*
> ```Go
> 	} else if backend == resources.SCBE {
> 		return NewScbeMounter(pluginConfig.ScbeRemoteConfig), nil
> 	} else {
> ```

You don't need this else, if all the others are false it will just result in the last one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/196)*

**Comment by ranhrl** [comment]
Could we in any way use this module? https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount.go

---

Review status: 0 of 18 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[remote/mounter/mounter_factory.go, line 35 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/196#-L8S_NxDDjTi_i30FVA3:-L8W1mWZ5ELKbSBC6cyC:b-yml55d) ([raw file](https://github.com/ibm/ubiquity/blob/019bdfe0c4fbdecd81ae51ddba64f6c51f35f90d/remote/mounter/mounter_factory.go#L35)):*
<details><summary><i>Previously, tzurE wrote…</i></summary><blockquote>

You don't need this else, if all the others are false it will just result in the last one.
</blockquote></details>

Right, but I think it's more readable this way and prevents a mistake of adding more code at the end of the function by mistake.

---

*[remote/mounter/block_device_utils/fs.go, line 31 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/196#-L8W3hbwUTiSL__xm8Dq:-L8W3hbwUTiSL__xm8Dr:bqbd7ay) ([raw file](https://github.com/ibm/ubiquity/blob/019bdfe0c4fbdecd81ae51ddba64f6c51f35f90d/remote/mounter/block_device_utils/fs.go#L31)):*
> ```Go
> const (
> 	NotMountedErrorMessage = "not mounted" // Error while umount device that is already unmounted
> 	TimeoutMilisecondMountCmdIsDeviceMounted = 20 * 1000 // max to wait for mount command
> ```

how did you determine the timeouts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/196#-:-L8W4UkgMc780yATQGby:bbf6gak)*

**Comment by ranhrl** [comment]
or even https://golang.org/src/syscall/syscall_linux.go?s=20289:20384#L786

---

Review status: 0 of 18 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/196#-:-L8W5IGTnhXlceEmfb6L:b7gn9r2)*

**Comment by shay-berman** [comment]
@ranhrl  review it today and approved.

**Pull request merged**
