### PR TITLE
Fix/ub 1099 add request id to all logs

### PR DESCRIPTION
**Pull request by olgashtivelman**
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/215)

### CODE REVIEW

**Comment by shay-berman** [comment]
Hi @olgashtivelman,
Before the review please do:
1. Resolve the "conflicts" (you will see a button "resolve conflicts" that will help u to do it)
2. Please add to the PR a description that explain the PR and also link to the k8s PR that related to it as well. 
3. Please do the same on the https://github.com/IBM/ubiquity-k8s/pull/191 as well.
Thanks

**Comment by olgashtivelman** [comment]
the k8s review link.
https://github.com/IBM/ubiquity-k8s/pull/191/

this is the change to add reqeuest_id and go routine id to the ubiquity + flex + provisioner logs so that we can follow a single request through out the product. (and also be able to identify which logs belong to which request in a multi-threaded server like ubiquity.)

**Comment by shay-berman** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[remote/client.go, line 181 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE0CZMEw9oJOgz--KN:-LEE0CZN4mN3BgR3espI:b-bpjx1m) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/remote/client.go#L181)):*
> ```Go
> 	detachRemoteURL := utils.FormatURL(s.storageApiURL, "volumes", detachRequest.Name, "detach")
> 	detachRequest.CredentialInfo = s.config.CredentialInfo
> 	response, err := utils.HttpExecute(s.httpClient, "PUT", detachRemoteURL, detachRequest, detachRequest.Context)
> ```

Olga, it doesn't make sense to add detachRequest,Context as another param for httpexecute, because the whole detachRequest is already passed, so it sending the same param twice.

this note relevant for all the changes here.

---

*[utils/http_utils.go, line 96 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE48v26bkW67d-bZFZ:-LEE48v3-q4BsQBD-Gzx:b-sr1mlx) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/utils/http_utils.go#L96)):*
> ```Go
> func HttpExecute(httpClient *http.Client, requestType string, requestURL string, rawPayload interface{}, request_context resources.RequestContext) (*http.Response, error) {
> 	logger := logs.GetLogger()
> 	payload, err := json.MarshalIndent(rawPayload, "", " ")
> ```

This is strange
So you also marshal the request inside the post as well?
so we actually passing twice the same data. Lets consider how to tune it.

---

*[utils/http_utils.go, line 108 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE3pyd9LcR_hbSRp5c:-LEE3pyd9LcR_hbSRp5d:bkph81n) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/utils/http_utils.go#L108)):*
> ```Go
> 
> 	//setting the headers for the request
> 	request.Header.Set("request-id", request_context.Id)
> ```

ok
here I would make it more generic, since request_context may additional keys in the future, then its better to add headers by on each key in the struct.  So it will be ready framework and not specifically for this ID.

---

*[utils/logs/go_logging_logger.go, line 54 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE5-z88oJ1XokN1VWF:-LEE5-z9115TqqwTuSh3:b85uvjz) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/utils/logs/go_logging_logger.go#L54)):*
> ```Go
> 	b := make([]byte, 64)
> 	b = b[:
>         
> ```

what is this red dots? not sure

---

*[utils/logs/go_logging_logger.go, line 64 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE6Uy_0NzlRfqV78nd:-LEE6Uy_0NzlRfqV78ne:b4wfwuh) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/utils/logs/go_logging_logger.go#L64)):*
> ```Go
> var GoIdToRequestIdMap = new(sync.Map)
> 
> func (l *goLoggingLogger) getGoIdAndContextString() string {
> ```

rename function name "getContextStringFromGoId"   so it will make more sense.

---

*[utils/logs/go_logging_logger.go, line 68 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE5ECZ3rblfoVBJ9cH:-LEE5ECZ3rblfoVBJ9cI:bjgvq8d) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/utils/logs/go_logging_logger.go#L68)):*
> ```Go
> 	context, exists := GoIdToRequestIdMap.Load(go_id)
> 	if !exists {
> 		context = resources.RequestContext{Id: "XXXXX"}
> ```

change it to "NA" (not applicable) instead of XXXX     or "-".
please mentioned it in the design wiki page.

---

*[utils/logs/go_logging_logger.go, line 72 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE5cFI3qlZg8Ssznap:-LEE5cFI3qlZg8Ssznaq:bt64dv7) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/utils/logs/go_logging_logger.go#L72)):*
> ```Go
> 		context = context.(resources.RequestContext)
> 	}
> 	return fmt.Sprintf("%d:%s", go_id, context.(resources.RequestContext).Id)
> ```

print first the requestConextID and then the go_id.
its more important and its like father of the goid, so it should be before.

as mentioned in the design wiki page.

---

*[utils/logs/go_logging_logger.go, line 105 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE6kSI7DWTzt2DTC0W:-LEE6kSI7DWTzt2DTC0X:bt3ttlv) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/utils/logs/go_logging_logger.go#L105)):*
> ```Go
> 	switch level {
> 	case DEBUG:
> 		l.logger.Debug(fmt.Sprintf("[%s] %s", goid_context_string, traceEnter), args)
> ```

you can prepare the string (fmt.Sprintf("[%s] %s", goid_context_string, traceEnter))  before th switch and just use it on every function below,
it will simplify the code here.

---

*[web_server/storage_api_handler.go, line 41 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE7xhpBhIfRbjPign6:-LEE7xhpBhIfRbjPign7:b-3m8ngk) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/web_server/storage_api_handler.go#L41)):*
> ```Go
> 
> func getContextFromRequest(req *http.Request) resources.RequestContext {
> 	return resources.RequestContext{Id: req.Header.Get("request-id")}
> ```

I would do here also something generic that will  go on all the expected keys and not only request-id.

BTW consider what happened if its not there, you should consider to return empty string.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/215)*

**Comment by olgashtivelman** [comment]
Review status: 0 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[remote/client.go, line 181 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE0CZMEw9oJOgz--KN:-LEd9cEZBc4CJyQEu8tk:b5z4rng) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/remote/client.go#L181)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

Olga, it doesn't make sense to add detachRequest,Context as another param for httpexecute, because the whole detachRequest is already passed, so it sending the same param twice.

this note relevant for all the changes here.
</blockquote></details>

yes you are right. meant to change it. 

---

*[utils/http_utils.go, line 96 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE48v26bkW67d-bZFZ:-LEdBpkLD0DKZfJp5TMX:bpuj63w) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/utils/http_utils.go#L96)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

This is strange
So you also marshal the request inside the post as well?
so we actually passing twice the same data. Lets consider how to tune it.
</blockquote></details>

this is not a new change from this review.
 not sure why we are parsing twice? where? 

---

*[utils/http_utils.go, line 108 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE3pyd9LcR_hbSRp5c:-LEdAEdN1BeHgPs0CZWM:b-eueyob) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/utils/http_utils.go#L108)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

ok
here I would make it more generic, since request_context may additional keys in the future, then its better to add headers by on each key in the struct.  So it will be ready framework and not specifically for this ID.
</blockquote></details>

I think that per your comment above i will remove the context from the header and only use it in the request as it is sent there anyways. 

---

*[utils/logs/go_logging_logger.go, line 54 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE5-z88oJ1XokN1VWF:-LEdASx70TQuZs-Anxf9:b-e9o30f) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/utils/logs/go_logging_logger.go#L54)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

what is this red dots? not sure
</blockquote></details>

what red dots? (I don't see any dots in the reiview..)

---

*[utils/logs/go_logging_logger.go, line 64 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE6Uy_0NzlRfqV78nd:-LEdFETF1JTx58Us_XoC:b-896fix) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/utils/logs/go_logging_logger.go#L64)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

rename function name "getContextStringFromGoId"   so it will make more sense.
</blockquote></details>

Done.

---

*[utils/logs/go_logging_logger.go, line 68 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE5ECZ3rblfoVBJ9cH:-LEdFI5g48aK7AUd4A_E:b-896fix) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/utils/logs/go_logging_logger.go#L68)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

change it to "NA" (not applicable) instead of XXXX     or "-".
please mentioned it in the design wiki page.
</blockquote></details>

Done.

---

*[utils/logs/go_logging_logger.go, line 72 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE5cFI3qlZg8Ssznap:-LEdFOiZ4-4wrqLIwSwo:bnyoaxa) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/utils/logs/go_logging_logger.go#L72)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

print first the requestConextID and then the go_id.
its more important and its like father of the goid, so it should be before.

as mentioned in the design wiki page.
</blockquote></details>

in the design wiki page the go-id is first... 
But I can change it in both.

---

*[utils/logs/go_logging_logger.go, line 105 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE6kSI7DWTzt2DTC0W:-LEdG2uHBBJgXJtl59Ip:b-896fix) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/utils/logs/go_logging_logger.go#L105)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

you can prepare the string (fmt.Sprintf("[%s] %s", goid_context_string, traceEnter))  before th switch and just use it on every function below,
it will simplify the code here.
</blockquote></details>

Done.

---

*[web_server/storage_api_handler.go, line 41 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE7xhpBhIfRbjPign6:-LEdG5fJ5FPCOttZzue0:b4e8k4v) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/web_server/storage_api_handler.go#L41)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

I would do here also something generic that will  go on all the expected keys and not only request-id.

BTW consider what happened if its not there, you should consider to return empty string.


</blockquote></details>

as mentioned above I am adding a new commit with the change of not sending the request id also in the header as you mentioned we send it twice. so this is no  longer relevant.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/215)*

**Comment by olgashtivelman** [comment]
Review status: 0 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[remote/client.go, line 181 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE0CZMEw9oJOgz--KN:-LEdIhvmCHbdOLzCwXHH:b-896fix) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/remote/client.go#L181)):*
<details><summary><i>Previously, olgashtivelman wrote…</i></summary><blockquote>

yes you are right. meant to change it. 
</blockquote></details>

Done.

---

*[utils/http_utils.go, line 108 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE3pyd9LcR_hbSRp5c:-LEdIlOo1DJzyKS0CkyY:b-896fix) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/utils/http_utils.go#L108)):*
<details><summary><i>Previously, olgashtivelman wrote…</i></summary><blockquote>

I think that per your comment above i will remove the context from the header and only use it in the request as it is sent there anyways. 
</blockquote></details>

Done.

---

*[web_server/storage_api_handler.go, line 41 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE7xhpBhIfRbjPign6:-LEdInq98uxDPCR0xOkp:b-896fix) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/web_server/storage_api_handler.go#L41)):*
<details><summary><i>Previously, olgashtivelman wrote…</i></summary><blockquote>

as mentioned above I am adding a new commit with the change of not sending the request id also in the header as you mentioned we send it twice. so this is no  longer relevant.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/215)*

**Comment by olgashtivelman** [comment]
shay-berman
please review the code changes and the comments.

---

Review status: 0 of 9 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/215#-:-LEe4x5F7TM2fcM1rWMo:b-87wii1)*

**Comment by olgashtivelman** [comment]
@shay-berman
please review the code changes and the comments.

---

Review status: 0 of 9 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/215#-:-LEe55ykBRFcWj6nTvNW:b-ygr5v)*

**Comment by shay-berman** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[remote/client.go, line 181 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE0CZMEw9oJOgz--KN:-LEdgZus0ACPOa9vMQzp:b-m0l33m) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/remote/client.go#L181)):*
<details><summary><i>Previously, olgashtivelman wrote…</i></summary><blockquote>

Done.
</blockquote></details>

but i don't see the fix?  i still see it twice (commit and put to the branch)

---

*[utils/http_utils.go, line 98 at r4](https://reviewable.io/reviews/ibm/ubiquity/215#-LEdh1Ml-pbgjQnkq-DN:-LEdh1Ml-pbgjQnkq-DO:bvvxemb) ([raw file](https://github.com/ibm/ubiquity/blob/2f195b4cf0520137b3b727eb8da6a2b9487ba6ba/utils/http_utils.go#L98)):*
> ```Go
> 	payload, err := json.MarshalIndent(rawPayload, "", " ")
> 
> 	logger.Info("Sending HTTPExecute request")
> ```

why its info?   i think it should be debug or maybe its not needed at all here.   if u want to keep it in debug then please move it few lines below to be close to the real newrequest function.

---

*[utils/logs/go_logging_logger.go, line 72 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE5cFI3qlZg8Ssznap:-LEelPJX9SbH27ga3uVj:bazapvi) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/utils/logs/go_logging_logger.go#L72)):*
<details><summary><i>Previously, olgashtivelman wrote…</i></summary><blockquote>

in the design wiki page the go-id is first... 
But I can change it in both.
</blockquote></details>

great
its better to see the reqID first

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/215)*

**Comment by olgashtivelman** [comment]
Review status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @shay-berman and @olgashtivelman)

---

*[utils/http_utils.go, line 98 at r4](https://reviewable.io/reviews/ibm/ubiquity/215#-LEdh1Ml-pbgjQnkq-DN:-LEht_aS9TGbaWDr2PUa:b-nnzygq) ([raw file](https://github.com/ibm/ubiquity/blob/2f195b4cf0520137b3b727eb8da6a2b9487ba6ba/utils/http_utils.go#L98)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

why its info?   i think it should be debug or maybe its not needed at all here.   if u want to keep it in debug then please move it few lines below to be close to the real newrequest function.
</blockquote></details>

I guess its here by mistake when I was trying to test something. i removed it.

---

*[remote/client.go, line 181 at r2](https://reviewable.io/reviews/ibm/ubiquity/215#-LEE0CZMEw9oJOgz--KN:-LEhtSWjDGbgTqa7gPW2:b-yws1ig) ([raw file](https://github.com/ibm/ubiquity/blob/9eddcde4c56218f46ab4b6f5497f696d069c35a0/remote/client.go#L181)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

but i don't see the fix?  i still see it twice (commit and put to the branch)
</blockquote></details>

now you can see it

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/215)*

**Comment by shay-berman** [comment]
:lgtm:

---

Reviewed 1 of 8 files at r1, 3 of 6 files at r2, 1 of 3 files at r4, 4 of 4 files at r5.
Review status: all files reviewed, 1 unresolved discussion (waiting on @shay-berman)

---

*[utils/http_utils.go, line 98 at r4](https://reviewable.io/reviews/ibm/ubiquity/215#-LEdh1Ml-pbgjQnkq-DN:-LEoQ15n3zxoqmxh6SfJ:bgkonad) ([raw file](https://github.com/ibm/ubiquity/blob/2f195b4cf0520137b3b727eb8da6a2b9487ba6ba/utils/http_utils.go#L98)):*
<details><summary><i>Previously, olgashtivelman wrote…</i></summary><blockquote>

I guess its here by mistake when I was trying to test something. i removed it.
</blockquote></details>

great, this is why we do code review :-)  and you review mine 

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/215#-:-LEoQJSSBFWI31ojjsdo:bnfp4nl)*

**Pull request merged**
