### PR TITLE
Fix/ub 621 image vulnerabilities

### PR DESCRIPTION
**Pull request by hfeish**
Remove sqlite3

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/207)

### CODE REVIEW

**Comment by shay-berman** [comment]
please remove the un relevant lines instead of putting them in comment, then send me again to review.

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[database/connection_test.go, line 19 at r1](https://reviewable.io/reviews/ibm/ubiquity/207#-LBtdlr-1fa6yekCj4dr:-LBtdlr-1fa6yekCj4ds:b-wcliim) ([raw file](https://github.com/ibm/ubiquity/blob/d8ba592e1ad53c823b27d573020865882b2dcc48/database/connection_test.go#L19)):*
> ```Go
> package database_test
> 
> /*
> ```

why you remove this file?

is it sqlite related only? doesn't look like

---

*[database/init.go, line 110 at r1](https://reviewable.io/reviews/ibm/ubiquity/207#-LBtdyAWD6WWVgiXV489:-LBtdyAWD6WWVgiXV48A:bgep8c9) ([raw file](https://github.com/ibm/ubiquity/blob/d8ba592e1ad53c823b27d573020865882b2dcc48/database/init.go#L110)):*
> ```Go
> }
> 
> /*
> ```

I don't like you put in comments
Just delete the un relevant lines instead of comment out.   no reason to leave it there.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/207#-:-LBteVw12iugYOOBpOOO:b-a00ypt)*

**Comment by shay-berman** [comment]
@fei, let me know when you apply my comments please.

---

Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/207#-:-LD6urZB2EpVUmbEyvyy:b-wp1cl4)*

**Comment by hfeish** [comment]
@Shay, I can start to apply this after finish the flex log, if it is not urgent, I will apply it after finish the idempotent issue, how do you think?

---

Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/207#-:-LDAH4Tt0_VLBMIaqotN:bxn4k0a)*

**Comment by shay-berman** [comment]
hi
please continue with this vulnerability thing after you finish the flex log.

and after vulnerability fix move on to provisioning idempotent (since idempotent will take u more time)
ok?

---

Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/207#-:-LDAMttK2BzpX0oqW4ws:b-hpzixn)*

**Comment by hfeish** [comment]
@shay-berman  OK

**Comment by hfeish** [comment]
Review status: 0 of 17 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[database/connection_test.go, line 19 at r1](https://reviewable.io/reviews/ibm/ubiquity/207#-LBtdlr-1fa6yekCj4dr:-LDFbRDT-5Yj4boACxNC:b-ytulcm) ([raw file](https://github.com/ibm/ubiquity/blob/d8ba592e1ad53c823b27d573020865882b2dcc48/database/connection_test.go#L19)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

why you remove this file?

is it sqlite related only? doesn't look like
</blockquote></details>

For sqlite, we can test it with a db file which exist 
But for postgres, we need a running postgres, so I think we cannot test it here, so remove it

---

*[database/init.go, line 110 at r1](https://reviewable.io/reviews/ibm/ubiquity/207#-LBtdyAWD6WWVgiXV489:-LDFaVTT2LS9QOGuz1no:b-toogs) ([raw file](https://github.com/ibm/ubiquity/blob/d8ba592e1ad53c823b27d573020865882b2dcc48/database/init.go#L110)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

I don't like you put in comments
Just delete the un relevant lines instead of comment out.   no reason to leave it there.
</blockquote></details>

Delete the un relevant lines

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/207)*

**Comment by shay-berman** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/207)*

**Comment by hfeish** [comment]
Review status: 14 of 17 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[database/connection_test.go, line 19 at r1](https://reviewable.io/reviews/ibm/ubiquity/207#-LBtdlr-1fa6yekCj4dr:-LDeapKV5r9Bum2pak3c:b-wuiui7) ([raw file](https://github.com/ibm/ubiquity/blob/d8ba592e1ad53c823b27d573020865882b2dcc48/database/connection_test.go#L19)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

yes and no

yes currently it tested sqlite but if you remove this unit test it means we have zero unit testing on database/connection.go which is not good.

So please try to add connection_test.go file that will test the open\close of the connection.go
you can use mocking ConnectionFactory maybe you should also add NewConnectionWithGlobalConnectionFactory() so you will be able to init the connection with mocked GlobalConnectionFactory.
Try to do it if you can so at least we will have unit test on this area as well.
</blockquote></details>

Add testCorrectFactory here, and in func(f *testCorrectFactory) newConnection(), new a *gorm.DB, with this we can test open(), and for close(), we test the case while   db== nil.

---

*[local/clients.go, line 31 at r2](https://reviewable.io/reviews/ibm/ubiquity/207#-LDVf_vHAcvukn6QMzw9:-LDecjda6sA4W4q27_7W:bu1xbut) ([raw file](https://github.com/ibm/ubiquity/blob/f05aee3b505045aacb447c637a8ade80af7e016d/local/clients.go#L31)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

I am not sure if you can remove this, since it will break scale for sure.

Instead, please put it in comment and send email to Gaurang S. Tapase that in dev branch we moving to postgress only (dropping sqlite) and they should be aware that the scale local client also need to change according (CC me as well).
</blockquote></details>

Sent email to Gaurang

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/207)*

**Comment by hfeish** [comment]
@shay-berman , please give comment here, thanks!

**Comment by shay-berman** [comment]
:lgtm:

---

Review status: 14 of 17 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[database/connection_test.go, line 19 at r1](https://reviewable.io/reviews/ibm/ubiquity/207#-LBtdlr-1fa6yekCj4dr:-LE3qpMd-YIC21NyN77U:b-mvmb1k) ([raw file](https://github.com/ibm/ubiquity/blob/d8ba592e1ad53c823b27d573020865882b2dcc48/database/connection_test.go#L19)):*
<details><summary><i>Previously, hfeish (Fei Huang) wrote…</i></summary><blockquote>

Add testCorrectFactory here, and in func(f *testCorrectFactory) newConnection(), new a *gorm.DB, with this we can test open(), and for close(), we test the case while   db== nil.
</blockquote></details>

Now its better thanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/207#-:-LE3qrWb989cA3CBmX7c:bnfp4nl)*

**Comment by hfeish** [comment]
Change back "openssl=1.0.2o-r0" which is latest version

**Pull request merged**
