### PR TITLE
moving to golang 1.9.1

### PR DESCRIPTION
**Pull request by midoblgsm**
Moving to golang 1.9.1
Signed-off-by: Mohamed Mohamed <mmohamed@us.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/129)

### CODE REVIEW

**Comment by aswarke** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/129#-:-KwBhCb_WE4XwCO1miPB:bnfp4nl)*

**Comment by shay-berman** [comment]
:lgtm:

go 1.9.1 minor release  has 2 security fixes
so its good to upgrade to it

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/129#-:-KwBkggKVkVL_3BhpIfL:b-hcgzjn)*

**Comment by shay-berman** [comment]
@midoblgsm  any reason why this is not merged?    any impediments?

**Comment by midoblgsm** [comment]
already covered by a previous PR

**Comment by midoblgsm** [comment]
can be merged at any time, you can do that @shay-berman

**Pull request closed without merging**
