### PR TITLE
Docker Managed Plugin System related enhancements

### PR DESCRIPTION
**Pull request by aswarke**
Pull request supporting 
1) #126 
2) #125 IBM/ubiquity-docker-plugin#52 IBM/ubiquity-docker-plugin#51, 
Make the following changes to spectrum-scale backend in order for it to work with Docker's Managed plugin system

Updating spectrum-scale SSH connector and adding methods for managing Lightweight volumes. Using ssh identity file to login in SSH connector

Updating Dockerfile with addition of openssh package to enable SSH connector within ubiquity container

Updating spectrum-scale mounter to use symlinks when incoming requests are from Docker engine

3) upcoming changes pending for #127

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/128)

### CODE REVIEW

**Comment by shay-berman** [comment]
Review status: 0 of 23 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[Dockerfile, line 10 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw502wPt76e0EOzEX0c:-Kw502wQanLccqGR7hNW:b-9n6y0r) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/Dockerfile#L10)):*
> ```Dockerfile
> 
> FROM alpine:latest
> RUN apk --no-cache add ca-certificates=20161130-r2 openssl=1.0.2k-r0 openssh
> ```

please remove the last openssl,    u have 2 in the same line

---

*[ubiquity-env.list, line 1 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw50UpAM4a-j8im_VJR:-Kw50UpAM4a-j8im_VJS:bfpc998) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/ubiquity-env.list#L1)):*
> ```
> # Ubiquity Server Config
> ```

why u need this file?
end of the day we will have all.env inside the stack file. like i did for k8s side

---

*[local/scbe/scbe.go, line 423 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw51BAAy7FQTXOpCkjj:-Kw51BAAy7FQTXOpCkjk:bosxoqg) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/local/scbe/scbe.go#L423)):*
> ```Go
> func (s *scbeLocalClient) GetCapabilities(capabilitiesRequest resources.GetCapabilitiesRequest) (resources.Capabilities, error) {
> 	defer s.logger.Trace(logs.DEBUG)()
> ```

if it generic then maybe it should be in the generic part.

---

*[local/spectrumscale/spectrumscale_nfs.go, line 194 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw6-SxxsLT-ZyazLV8j:-Kw6-SxxsLT-ZyazLV8k:bkhi5if) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/local/spectrumscale/spectrumscale_nfs.go#L194)):*
> ```Go
> 	defer s.spectrumClient.logger.Println("spectrumNfsLocalClient: GetCapabilities finish")
> 
> 	return resources.Capabilities{Scope:"global"}, nil
> ```

any reason not to use global?
maybe it should be a generic

---

*[local/spectrumscale/connectors/rest.go, line 336 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw51gpN3pk4haD5WO6R:-Kw51gpN3pk4haD5WO6S:b-v810sg) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/local/spectrumscale/connectors/rest.go#L336)):*
> ```Go
> 
> 	//open permissions on enclosing fileset
> 	args := []string{ "777", path.Join(mountpoint, filesetName)}
> ```

why 777?
be more secure please

---

*[remote/client.go, line 102 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw52A-mqPM1tf2hq4S8:-Kw52A-mqPM1tf2hq4S9:b-3rg8cl) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/remote/client.go#L102)):*
> ```Go
> 
> 	var volume resources.Volume
> 	if removeVolumeRequest.ContainerOrchestrator == "docker" {
> ```

1. please explain tje logic here.   what if its k8s??
add docstring please because ita not clear.

2. put the "docker" as const and use it in all places u set this attr.

---

*[remote/client.go, line 231 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw600m8B74yS9GkgtDg:-Kw600m8B74yS9GkgtDh:baq6biq) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/remote/client.go#L231)):*
> or == "docker" {
> 		volumeConfig["ContainerOrchestrator"] = "docker"
> 	}
again please use const for "docker"

---

*[resources/resources.go, line 76 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw60J0J9U-AyF5SRMFE:-Kw60J0J9U-AyF5SRMFF:bj2tr3) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/resources/resources.go#L76)):*
> ```Go
> const OptionNameForVolumeFsType = "fstype"                // the option name of the fstype and also the key in the volumeConfig
> const ScbeDefaultPort = 8440                              // the default port for SCBE management
> const DockerPropagatedMount = "/ubiquity"                 // Mountpoint, within the plugin container,for all Docker volumes
> ```

1. why do we have Propogate mount inside the ubiquity server?   this is only docker related.
2. anyway please create const for "ubiquity" and use it inside the pathtomountubiquityblockdevice and also for the dockerpropogatemount.   lets try to reduce duplication of strings.

---

*[utils/utils.go, line 283 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw60zL_5skrYWeKw5u8:-Kw60zLaeUotDspVt9sz:bb8um7j) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/utils/utils.go#L283)):*
> ```Go
> }
> 
> func LoadUbiquityPluginConfig() (resources.UbiquityPluginConfig, error) {
> ```

1. why this function is inside the backend?   it should be only in the plugin side,
please move it and also make sure you cover it with unit testing.

---

*[utils/utils.go, line 287 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw61IM1_Tw6HQv-aTZs:-Kw61IM1_Tw6HQv-aTZt:b-dnllol) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/utils/utils.go#L287)):*
> ```Go
> 	config := resources.UbiquityPluginConfig{}
> 
> 	config.LogLevel = os.Getenv("LOG_LEVEL")
> ```

you forgot to add validation on all the environments

please validate each env you expect to get, and if its empty please raise error
if there are default values please set them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/128)*

**Comment by shay-berman** [comment]
Hi @amit

Great effort to make the docker plugin v2!

I conducted code review on this PR, please review and apply them.

Thanks

**Comment by aswarke** [comment]
*[local/spectrumscale/spectrumscale_nfs.go, line 194 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw6-SxxsLT-ZyazLV8j:-Kwg4L4AZdQg0UGrL1zT:b-q2jkri) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/local/spectrumscale/spectrumscale_nfs.go#L194)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

any reason not to use global?
maybe it should be a generic
</blockquote></details>

Spectrum Scale volumes are global and in general all ubiquity based volumes are global with respect to Capabilities. I have explained in my previous comment about the need to support Capabilities API for every backend, which is the right direction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/128)*

**Comment by aswarke** [comment]
Review status: 0 of 23 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[Dockerfile, line 10 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw502wPt76e0EOzEX0c:-KwgEphUOZqDMa0NBV2q:b41irzk) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/Dockerfile#L10)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

please remove the last openssl,    u have 2 in the same line
</blockquote></details>

The last one is openssh and NOT openssl. they are not the same

---

*[ubiquity-env.list, line 1 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw50UpAM4a-j8im_VJR:-Kwg3CPC9JJ4OUBXyII1:b-o36btx) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/ubiquity-env.list#L1)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

why u need this file?
end of the day we will have all.env inside the stack file. like i did for k8s side
</blockquote></details>

What is stack file ? Kubernetes and Docker work differently. There are multiple ways of setting docker container env at runtime . Instead of of specifying everything on command line, it's easier to specify them in a file and let docker read env from the file . User can use this method or use their own method. See https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e-env-env-file

---

*[local/scbe/scbe.go, line 423 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw51BAAy7FQTXOpCkjj:-Kwg3vGZbkOgOwnITySW:b8eg26e) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/local/scbe/scbe.go#L423)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

if it generic then maybe it should be in the generic part.
</blockquote></details>

This is not generic. It would differ going ahead in the future. Right it seems same because it's Docker Initial API for Capabilities . Docker will be defining more properties in Capabilities . Each Storage system will have it's unique capabilities .I'm setting the stage here for future changes to Capabilities API . 

---

*[local/spectrumscale/connectors/rest.go, line 336 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw51gpN3pk4haD5WO6R:-Kwg4lF0p4WqbXl3TKdW:b-pojgda) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/local/spectrumscale/connectors/rest.go#L336)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

why 777?
be more secure please
</blockquote></details>

This is the behavior for Scale as before. This needs to be 777 for now and will change with future inputs and testing from scale team

---

*[remote/client.go, line 102 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw52A-mqPM1tf2hq4S8:-Kwg52ahlLwqpCnw9zAS:b-73wm53) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/remote/client.go#L102)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

1. please explain tje logic here.   what if its k8s??
add docstring please because ita not clear.

2. put the "docker" as const and use it in all places u set this attr.
</blockquote></details>

The logic with respect to scale is different. With respect to Docker, we need to create symlinks inside container . For other orchestrators, its the previous default approach .  This approach is needed to make sure mounter for scale works smoothly across Docker and Kubernetes . 

I Will create constant for Docker.

---

*[remote/client.go, line 231 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw600m8B74yS9GkgtDg:-KwgExgxv4VYyOtV0AJP:bb6un1j) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/remote/client.go#L231)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

> or == "docker" {
> 		volumeConfig["ContainerOrchestrator"] = "docker"
> 	}
again please use const for "docker"
</blockquote></details>

Done

---

*[resources/resources.go, line 76 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw60J0J9U-AyF5SRMFE:-Kwg6OqhBy-MgBG-RX84:b-nbosyz) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/resources/resources.go#L76)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

1. why do we have Propogate mount inside the ubiquity server?   this is only docker related.
2. anyway please create const for "ubiquity" and use it inside the pathtomountubiquityblockdevice and also for the dockerpropogatemount.   lets try to reduce duplication of strings.

</blockquote></details>

This is docker and scale related change.  PropagatedMount is needed inside ubiquity-docker-plugin container. Most of the logic is within mounter code and best to have constants inside resources package.
Created const for ubiquity and updated PathToMountUbiquityBlockDevice

---

*[utils/utils.go, line 283 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw60zL_5skrYWeKw5u8:-KwgDE387TrKjA4CCUyP:bmv0mst) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/utils/utils.go#L283)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

1. why this function is inside the backend?   it should be only in the plugin side,
please move it and also make sure you cover it with unit testing.

</blockquote></details>

This function is a utility function like loadConfig. It is best to have all Env related functions in the same place.  This should remain here.

---

*[utils/utils.go, line 287 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/128#-Kw61IM1_Tw6HQv-aTZs:-KwgDzL1UmQPn94bK1Du:b-d2ucvd) ([raw file](https://github.com/ibm/ubiquity/blob/07760d2599d92dac6dabe003cb25cd4f7148dfc2/utils/utils.go#L287)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

you forgot to add validation on all the environments

please validate each env you expect to get, and if its empty please raise error
if there are default values please set them.
</blockquote></details>

This is correct behavior . The default values are set in config.json NOT here . 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/128)*

**Comment by shay-berman** [comment]
close this Pull Request - When ever Docker Swarm will become high priority then we will open this PR again.  I will keep the Capability branch anyway but no need to keep this PR if we don't plan to merge it in the near future.

**Pull request closed without merging**
