### PR TITLE
Feature/ssl updates to images

### PR DESCRIPTION
**Pull request by ranhrl**
1. Created default values for the environment variables regarding SSL attributes.
2. Adjust the creation of keys and certificates in startup in case not provided from external source.

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/132)

### CODE REVIEW

**Comment by shay-berman** [comment]
please review my comments and apply few fixed then u ready to merge

---

Review status: 0 of 6 files reviewed at latest revision, 11 unresolved discussions.

---

*[docker-entrypoint.sh, line 4 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/132#-KwfxWZm9WdJb17bjKxO:-KwfxWZm9WdJb17bjKxP:bc0907q) ([raw file](https://github.com/ibm/ubiquity/blob/f4c1fee39cd4a947ec3c8ab23180ae33cb038f69/docker-entrypoint.sh#L4)):*
> ```Shell
> set -e
> 
> export SSL_PRIVATE_DIR=`dirname $UBIQUITY_SERVER_CERT_PRIVATE`
> ```

i believe u should check first if $UBIQUITY_SERVER_CERT_PRIVATE exist   [ -z "$UBIQUITY_SERVER_CERT_PRIVATE" ]
because if not the dirname command will be broken  
same below

---

*[docker-entrypoint.sh, line 7 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/132#-Kwfxoi5rOiIYiceDsX2:-Kwfxoi5rOiIYiceDsX3:bdzd5i1) ([raw file](https://github.com/ibm/ubiquity/blob/f4c1fee39cd4a947ec3c8ab23180ae33cb038f69/docker-entrypoint.sh#L7)):*
> ```Shell
> export SSL_PUBLIC_DIR=`dirname $UBIQUITY_SERVER_CERT_PUBLIC`
> 
> # to be used when ubiquity will not run as root
> ```

for GA v1 
ubiquity will run as root user inside the container, so i think u should remove this comment

---

*[docker-entrypoint.sh, line 14 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/132#-Kwfy1J4lzRo8vZNF4ML:-Kwfy1J4lzRo8vZNF4MM:b-kurd3q) ([raw file](https://github.com/ibm/ubiquity/blob/f4c1fee39cd4a947ec3c8ab23180ae33cb038f69/docker-entrypoint.sh#L14)):*
> ```Shell
> configure_ssl() {
>     echo "Creating SSL directory $SSL_PRIVATE_DIR and setting ownership to user postgres ..."
>     mkdir -p $SSL_PRIVATE_DIR
> ```

be aware that this dir will automatic be created already, so make sure mkdir -p is ok with it.

---

*[docker-entrypoint.sh, line 43 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/132#-KwfyjvHS3xjww8XCxRb:-KwfyjvIws4cB2Ao9rxi:bl7nf1e) ([raw file](https://github.com/ibm/ubiquity/blob/f4c1fee39cd4a947ec3c8ab23180ae33cb038f69/docker-entrypoint.sh#L43)):*
> ```Shell
>         chown ${USER}:${GROUP} $UBIQUITY_SERVER_CERT_PUBLIC
>         chmod 600 $UBIQUITY_SERVER_CERT_PUBLIC
>         echo "Creating default SSL certificates for ubiquity - done!"
> ```

if u didn't echo the file name(with path) of the private and public key, so please do so. so if someone from out side want to get these certificates he will know where to search it.

---

*[scripts/ubiquity-postgresql/Dockerfile, line 6 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/132#-KwfzTcV-fpDEpz9gyrN:-KwfzTcV-fpDEpz9gyrO:b-ecj8z5) ([raw file](https://github.com/ibm/ubiquity/blob/f4c1fee39cd4a947ec3c8ab23180ae33cb038f69/scripts/ubiquity-postgresql/Dockerfile#L6)):*
> ```Dockerfile
>     UBIQUITY_DB_CERT_PUBLIC="/var/lib/postgresql/ssl/private/ubiquity-db.crt"
> 
> RUN PGSSL_PRIVATE="`dirname $UBIQUITY_DB_CERT_PRIVATE`" && mkdir -p "$PGSSL_PRIVATE" && chown -R postgres:postgres "$PGSSL_PRIVATE" && chmod 777 "$PGSSL_PRIVATE"
> ```

r u sure its hardcoded "postgres" user? is it the linux user inside the container going to be always postgres, or we allow to change it?
i guess we allow to change the postgres DB user name and not the linux user name, just checking.

---

*[scripts/ubiquity-postgresql/ubiquity-docker-entrypoint.sh, line 12 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/132#-KwfzwWW3my1iRG2962B:-KwfzwWW3my1iRG2962C:bdcx354) ([raw file](https://github.com/ibm/ubiquity/blob/f4c1fee39cd4a947ec3c8ab23180ae33cb038f69/scripts/ubiquity-postgresql/ubiquity-docker-entrypoint.sh#L12)):*
> ```Shell
> set -e
> 
> export PGSSL_PRIVATE_DIR="`dirname $UBIQUITY_DB_CERT_PRIVATE`"
> ```

same thing i mentioned above

---

*[scripts/ubiquity-postgresql/ubiquity-docker-entrypoint.sh, line 29 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/132#-Kwg04TLG6qg72dUd_mr:-Kwg04TLG6qg72dUd_ms:b-h746zg) ([raw file](https://github.com/ibm/ubiquity/blob/f4c1fee39cd4a947ec3c8ab23180ae33cb038f69/scripts/ubiquity-postgresql/ubiquity-docker-entrypoint.sh#L29)):*
> ```Shell
>     fi
> 
>     if [ ! -s "$UBIQUITY_DB_CERT_PUBLIC" ]; then
> ```

i think change it from -s to -e
because if it exist with zero size u still don't want to overwrite it because the customer decided to us it.
so its better to raise with bad certificate rather then create and overriding something the customer did.

the same for the  -s in upper file in this review

---

*[scripts/ubiquity-postgresql/ubiquity-docker-entrypoint.sh, line 52 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/132#-Kwg-lCxMFH8B38c8Qzw:-Kwg-lCxMFH8B38c8Qzx:bhrdqyg) ([raw file](https://github.com/ibm/ubiquity/blob/f4c1fee39cd4a947ec3c8ab23180ae33cb038f69/scripts/ubiquity-postgresql/ubiquity-docker-entrypoint.sh#L52)):*
> ```Shell
>         chown postgres $UBIQUITY_DB_CERT_PUBLIC
>         chmod 600 $UBIQUITY_DB_CERT_PUBLIC
>     fi
> ```

please add else with echo "using existing certificate files X Y Z"

---

*[scripts/ubiquity-postgresql/ubiquity-docker-entrypoint.sh, line 53 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/132#-Kwg-7RRrxddgI1ZIi0b:-Kwg-7RRrxddgI1ZIi0c:b-g7o6o0) ([raw file](https://github.com/ibm/ubiquity/blob/f4c1fee39cd4a947ec3c8ab23180ae33cb038f69/scripts/ubiquity-postgresql/ubiquity-docker-entrypoint.sh#L53)):*
> ```Shell
>         chmod 600 $UBIQUITY_DB_CERT_PUBLIC
>     fi
> fi
> ```

for debug, just add else here with echo "skip creating default certificate"

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh, line 21 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/132#-Kwg0oFfZzw3WFQe7qwK:-Kwg0oFfZzw3WFQe7qwL:bajbfru) ([raw file](https://github.com/ibm/ubiquity/blob/f4c1fee39cd4a947ec3c8ab23180ae33cb038f69/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh#L21)):*
> ```Shell
> mv /tmp/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf
> 
> sed -i 's/#ssl/ssl/g' /var/lib/postgresql/data/postgresql.conf
> ```

POSTGRESQL_CONF=/var/lib/postgresql/data/postgresql.conf
and just reuse it in all the places here (reduce duplication)

---

*[scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-user-db.sh, line 6 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/132#-Kwg17TBePpR-4V61Kpf:-Kwg17TCIP2ngiiP_vQp:b-k73z76) ([raw file](https://github.com/ibm/ubiquity/blob/f4c1fee39cd4a947ec3c8ab23180ae33cb038f69/scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-user-db.sh#L6)):*
> ```Shell
> echo "Creating user for ubiquity.."
> 
> if [ -z "$UBIQUITY_DB_USERNAME" ]; then
> ```

thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/132#-:-Kwg1D16_9iTQ44DuWHd:b-al5t1c)*

**Comment by ranhrl** [comment]
Review status: 0 of 6 files reviewed at latest revision, 11 unresolved discussions.

---

*[docker-entrypoint.sh, line 4 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/132#-KwfxWZm9WdJb17bjKxO:-KwjYeG5M_38RDSktzzK:bavetio) ([raw file](https://github.com/ibm/ubiquity/blob/f4c1fee39cd4a947ec3c8ab23180ae33cb038f69/docker-entrypoint.sh#L4)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

i believe u should check first if $UBIQUITY_SERVER_CERT_PRIVATE exist   [ -z "$UBIQUITY_SERVER_CERT_PRIVATE" ]
because if not the dirname command will be broken  
same below
</blockquote></details>

It is safe to assume that it exists since it is defined in the Docekrfile

---

*[docker-entrypoint.sh, line 14 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/132#-Kwfy1J4lzRo8vZNF4ML:-KwjZ7nvwKYy13PtTIYb:b-5hnvjc) ([raw file](https://github.com/ibm/ubiquity/blob/f4c1fee39cd4a947ec3c8ab23180ae33cb038f69/docker-entrypoint.sh#L14)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

be aware that this dir will automatic be created already, so make sure mkdir -p is ok with it.
</blockquote></details>

mkdir -p is idempotent 

---

*[scripts/ubiquity-postgresql/Dockerfile, line 6 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/132#-KwfzTcV-fpDEpz9gyrN:-Kwj_LOrBh1F2GbqFqON:brj7xsr) ([raw file](https://github.com/ibm/ubiquity/blob/f4c1fee39cd4a947ec3c8ab23180ae33cb038f69/scripts/ubiquity-postgresql/Dockerfile#L6)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

r u sure its hardcoded "postgres" user? is it the linux user inside the container going to be always postgres, or we allow to change it?
i guess we allow to change the postgres DB user name and not the linux user name, just checking.
</blockquote></details>

You are correct, this is the linux user, the image does not allow to change it.

---

*[scripts/ubiquity-postgresql/ubiquity-docker-entrypoint.sh, line 53 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/132#-Kwg-7RRrxddgI1ZIi0b:-KwjcDgPVDsecyYXQtp9:bsaihoh) ([raw file](https://github.com/ibm/ubiquity/blob/f4c1fee39cd4a947ec3c8ab23180ae33cb038f69/scripts/ubiquity-postgresql/ubiquity-docker-entrypoint.sh#L53)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

for debug, just add else here with echo "skip creating default certificate"
</blockquote></details>

not really required, this happens only when running the container with command other then postgres (bash for example)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/132)*

**Comment by shay-berman** [comment]
Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/132)*

**Comment by shay-berman** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[docker-entrypoint.sh, line 4 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/132#-KwfxWZm9WdJb17bjKxO:-Kwjq5sK6SP6ImZzgM7K:b-6veb4a) ([raw file](https://github.com/ibm/ubiquity/blob/f4c1fee39cd4a947ec3c8ab23180ae33cb038f69/docker-entrypoint.sh#L4)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

It is safe to assume that it exists since it is defined in the Docekrfile
</blockquote></details>

RAN

it just failed because of this

root@tzur-ubiquity-master:~# kk logs -n ubiquity ubiquity-707244936-0p6dm
BusyBox v1.26.2 (2017-06-11 06:38:32 GMT) multi-call binary.

Usage: dirname FILENAME

Strip non-directory suffix from FILENAME
Creating SSL directory  and setting ownership to user postgres ...
BusyBox v1.26.2 (2017-06-11 06:38:32 GMT) multi-call binary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/132)*

**Pull request merged**
