### PR TITLE
UB-379: update SCB interface name to Containers

### PR DESCRIPTION
**Pull request by alonm**
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity/144)

### CODE REVIEW

**Comment by shay-berman** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[ibm-block-storage-via-scbe.md, line 24 at r1](https://reviewable.io:443/reviews/ibm/ubiquity/144#-Kz36mSwLf4YDPnvUZKQ:-Kz36mSwLf4YDPnvUZKR:b-65yr1e) ([raw file](https://github.com/ibm/ubiquity/blob/994d30c2c43591842f7c4ee044549196a924a2d1/ibm-block-storage-via-scbe.md#L24)):*
> ```Markdown
> 
>        1. Log into Spectrum Control Base Edition server at https://SCBE_IP_address:8440.
>        2. Add a Ubiquity interface. Note: The Ubiqity interface username and the password will be used in the ubiquity server configuration file below. In this SCBE version, Ubiquity interface is referred to as “Containers interface” (this will be modified in future version).
> ```

its should be "Enabler for Container"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/144#-:-Kz37YWSz7pwVRFWgZzx:bnfp4nl)*

**Comment by shay-berman** [comment]
please merge only after everyone upgrade to the new SCBE version with the new interface.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/144#-:-Kz38mDZHXZCcnilC9ew:b5g0zz7)*

**Comment by liortamari** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/144)*

**Comment by liortamari** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity/144#-:-Kz3IVGBH6bS_-RZ123-:bnfp4nl)*

**Pull request merged**
